DATA LIST FILE='C:\Countries\PK7A\PKVA7AFL.DAT' RECORDS=1
  /
  QHCLUST     1-4   
  QHNUMBER    5-8   
  QLINE       9-10  
  QREGION    11-11  
  QDIST      12-14  
  QTYPE      15-15  
  QQTYPE     16-16  
  QINTD      17-18  
  QINTM      19-20  
  QINTY      21-24  
  QINTNUM    25-28  
  QRESULT    29-29  
  QVISITS    30-30  
  QLANGQ     31-32  
  QLANGI     33-34  
  QLANGR     35-36  
  QTRANS     37-37  
  QSUPERV    38-41  
  QFEDIT     42-45  
  QKEYER     46-47  
  QINTC      48-51  
  QINTCD     52-56  
  QWEIGHT    57-64  
  QV101$1    65-66  
  QV101$2    67-68  
  QV101$3    69-70  
  QV101$4    71-72  
  QV101$5    73-74  
  QV101$6    75-76  
  QV101$7    77-78  
  QV103$1    79-79  
  QV103$2    80-80  
  QV103$3    81-81  
  QV103$4    82-82  
  QV103$5    83-83  
  QV103$6    84-84  
  QV103$7    85-85  
  QV104$1    86-87  
  QV104$2    88-89  
  QV104$3    90-91  
  QV104$4    92-93  
  QV104$5    94-95  
  QV104$6    96-97  
  QV104$7    98-99  
  QV105$1   100-101 
  QV105$2   102-103 
  QV105$3   104-105 
  QV105$4   106-107 
  QV105$5   108-109 
  QV105$6   110-111 
  QV105$7   112-113 
  QV106$1   114-115 
  QV106$2   116-117 
  QV106$3   118-119 
  QV106$4   120-121 
  QV106$5   122-123 
  QV106$6   124-125 
  QV106$7   126-127 
  QV107$1   128-128 
  QV107$2   129-129 
  QV107$3   130-130 
  QV107$4   131-131 
  QV107$5   132-132 
  QV107$6   133-133 
  QV107$7   134-134 
  QV108$1   135-135 
  QV108$2   136-136 
  QV108$3   137-137 
  QV108$4   138-138 
  QV108$5   139-139 
  QV108$6   140-140 
  QV108$7   141-141 
  QV109$1   142-142 
  QV109$2   143-143 
  QV109$3   144-144 
  QV109$4   145-145 
  QV109$5   146-146 
  QV109$6   147-147 
  QV109$7   148-148 
  QV110$1   149-150 
  QV110$2   151-152 
  QV110$3   153-154 
  QV110$4   155-156 
  QV110$5   157-158 
  QV110$6   159-160 
  QV110$7   161-162 
  QV201H    163-164 
  QV201M    165-166 
  QV204D    167-168 
  QV204M    169-170 
  QV204Y    171-174 
  QV204BD   175-176 
  QV204BM   177-178 
  QV204BY   179-182 
  QV205     183-184 
  QV206     185-185 
  QV207     186-186 
  QV208     187-188 
  QV209     189-189 
  QV210     190-191 
  QV211     192-193 
  QV212     194-194 
  QV214     195-196 
  QV215     197-197 
  QV216     198-199 
  QV217     200-201 
  QV217A    202-202 
  QVELIG    203-203 
  QV204BC   204-207 
  QV204BF   208-208 
  QV204C    209-212 
  QV204F    213-213 
  QV204CD   214-218 
  QV204DI   219-220 
  QV301     221-221 
  QV302     222-223 
  QV303A    224-225 
  QV303B    226-227 
  QV303C    228-229 
  QV304     230-230 
  QV305A    231-232 
  QV305B    233-234 
  QV305C    235-236 
  QV305D    237-238 
  QV307     239-239 
  QV307A    240-240 
  QV308     241-241 
  QV309U    242-242 
  QV309N    243-244 
  QV310     245-245 
  QV311     246-246 
  QV312     247-248 
  QV313U    249-249 
  QV313N    250-251 
  QV314U    252-252 
  QV314N    253-254 
  QV315     255-255 
  QV316     256-257 
  QV318     258-258 
  QV321     259-259 
  QV501     260-260 
  QV502     261-261 
  QV503     262-262 
  QV504     263-263 
  QV505     264-264 
  QV506A    265-265 
  QV506B    266-266 
  QV506C    267-267 
  QV506D    268-268 
  QV506E    269-269 
  QV506F    270-270 
  QV506G    271-271 
  QV506H    272-272 
  QV506I    273-273 
  QV506J    274-274 
  QV506K    275-275 
  QV506L    276-276 
  QV506X    277-277 
  QV507     278-278 
  QV508U    279-279 
  QV508N    280-281 
  QV509     282-282 
  QV510     283-283 
  QV510A    284-284 
  QV511     285-285 
  QV511AU   286-286 
  QV511AN   287-288 
  QV511B    289-289 
  QV512     290-290 
  QV512A    291-291 
  QV513     292-292 
  QV514     293-293 
  QV515     294-294 
  QV515AU   295-295 
  QV515AN   296-297 
  QV515B    298-298 
  QV515C    299-299 
  QV516     300-300 
  QV516AU   301-301 
  QV516AN   302-303 
  QV516B    304-304 
  QV516C    305-305 
  QV516D    306-306 
  QV517     307-307 
  QV517A    308-309 
  QV517B    310-310 
  QV518     311-311 
  QV518AU   312-312 
  QV518AN   313-314 
  QV520     315-315 
  QV520A    316-316 
  QV521     317-317 
  QV521AU   318-318 
  QV521AN   319-320 
  QV522     321-321 
  QV522AU   322-322 
  QV522AN   323-324 
  QV523     325-325 
  QV523AU   326-326 
  QV523AN   327-328 
  QV524     329-329 
  QV525     330-330 
  QV526     331-331 
  QV527     332-332 
  QV527AU   333-333 
  QV527AN   334-335 
  QV527B    336-336 
  QV527C    337-337 
  QV528     338-338 
  QV528AU   339-339 
  QV528AN   340-341 
  QV528B    342-342 
  QV529     343-343 
  QV530     344-344 
  QV530AU   345-345 
  QV530AN   346-347 
  QV530B    348-348 
  QV531     349-349 
  QV532     350-350 
  QV532AU   351-351 
  QV532AN   352-353 
  QV532B    354-354 
  QV533     355-355 
  QV533AU   356-356 
  QV533AN   357-358 
  QV533B    359-359 
  QV534     360-360 
  QV535     361-361 
  QV536     362-362 
  QV536AU   363-363 
  QV536AN   364-365 
  QV536B    366-367 
  QV537     368-368 
  QV538     369-369 
  QV538AU   370-370 
  QV538AN   371-372 
  QV538B    373-373 
  QV539     374-374 
  QV540     375-375 
  QV541     376-376 
  QV541AU   377-377 
  QV541AN   378-379 
  QV542     380-380 
  QV543     381-381 
  QV544     382-382 
  QV545     383-383 
  QV545A    384-384 
  QV546     385-385 
  QV546AU   386-386 
  QV546AN   387-388 
  QV547     389-389 
  QV548     390-390 
  QV549     391-391 
  QV550     392-392 
  QV551     393-393 
  QV551AU   394-394 
  QV551AN   395-396 
  QV551B    397-397 
  QV551C    398-398 
  QV552     399-399 
  QV553$1   400-400  (A)
  QV553$2   401-401  (A)
  QV553$3   402-402  (A)
  QV553$4   403-403  (A)
  QV553$5   404-404  (A)
  QV553$6   405-405  (A)
  QV553$7   406-406  (A)
  QV554     407-407 
  QV555     408-408 
  QV556     409-409 
  QV602U    410-410 
  QV602N    411-412 
  QV602A    413-413 
  QV602BU   414-414 
  QV602BN   415-416 
  QV603U    417-417 
  QV603N    418-419 
  QV604     420-420 
  QV605     421-421 
  QV606     422-422 
  QV607     423-423 
  QV607A    424-424 
  QV608     425-425 
  QV608AU   426-426 
  QV608AN   427-428 
  QV608B    429-429 
  QV609     430-430 
  QV610     431-431 
  QV610AA   432-432 
  QV610AB   433-433 
  QV610AC   434-434 
  QV610AD   435-435 
  QV610AE   436-436 
  QV610AX   437-437 
  QV613     438-438 
  QV615U    439-439 
  QV615N    440-441 
  QV616     442-442 
  QV617     443-443 
  QV617A    444-444 
  QV618     445-445 
  QV620     446-446 
  QV620AU   447-447 
  QV620AN   448-449 
  QV622     450-450 
  QV623     451-457  (A)
  QV624U    458-458 
  QV624N    459-460 
  QV625U    461-461 
  QV625N    462-463 
  QV625A    464-464 
  QV625B    465-465 
  QV626     466-466 
  QV627     467-467 
  QV628     468-468 
  QV629     469-469 
  QV630     470-470 
  QV633     471-471 
  QV634     472-472 
  QV634AU   473-473 
  QV634AN   474-475 
  QV635     476-476 
  QV636     477-477 
  QV637     478-478 
  QV638     479-479 
  QV638A    480-480 
  QV638B    481-482 
  QV638D    483-483 
  QV638E    484-484 
  QV638F    485-485 
  QV640A    486-486 
  QV640B    487-487 
  QV640C    488-488 
  QV640D    489-489 
  QV641U    490-490 
  QV641N    491-492 
  QV642U    493-493 
  QV642N    494-495 
  QV643     496-496 
  QV644     497-497 
  QV644A    498-498 
  QV645     499-499 
  QV645AA   500-500 
  QV645AB   501-501 
  QV645AC   502-502 
  QV645AD   503-503 
  QV645AX   504-504 
  QV702     505-505 
  QV703     506-514  (A)
  QV704     515-515 
  QV705     516-516 
  QV706     517-518 
  QV707     519-520 
  QV708     521-521 
  QV709     522-535  (A)
  QV710     536-536 
  QV711     537-537 
  QV712     538-538 
  QV713     539-539 
  QV714     540-540 
  QV715     541-541 
  QV716     542-542 
  QV717     543-543 
  QV718     544-545 
  QV720     546-546 
  QV721     547-547 
  QV722     548-548 
  QV726     549-549 
  QV727     550-550 
  QV728     551-551 
  QV729     552-552 
  QV730     553-553 
  QV731     554-554 
  QV732     555-555 
  QV733     556-556 
  QV734     557-557 
  QV802     558-558 
  QV803     559-559 
  QV804     560-560 
  QV805     561-561 
  QV806     562-563 
  QV807     564-565 
  QV808     566-566 
  QV808A    567-567 
  QV808B    568-568 
  QV809     569-569 
  QV810     570-570 
  QV811     571-571 
  QV812     572-572 
  QV813     573-574 
  QV814     575-575 
  QV815     576-576 
  QV816     577-577 
  QV817     578-578 
  QV818     579-579 
  QV819     580-580 
  QV820     581-581 
  QV821     582-582 
  QV822     583-583 
  QV823     584-584 
  QV824U    585-585 
  QV824N    586-587 
  QV825     588-588 
  QV826     589-589 
  QV827     590-590 
  QV828     591-591 
  QV829     592-592 
  QV830     593-593 
  QV831     594-594 
  QV832     595-595 
  QV833U    596-596 
  QV833N    597-598 
  QV834     599-599 
  QV835     600-600 
  QV836U    601-601 
  QV836N    602-603 
  QV837     604-604 
  QV838     605-605 
  QV839     606-606 
  QV840     607-607 
  QV841     608-608 
  QV901     609-609 
  QV902     610-611 
  QV903U    612-612 
  QV903N    613-614 
  QV904     615-615 
  QV905     616-616 
  QV906     617-617 
  QV1001U   618-618 
  QV1001N   619-620 
  QV1002    621-621 
  QV1003    622-622 
  QV1004    623-623 
  QV1005    624-636  (A)
  QV1006    637-647  (A)
  QV1007    648-657  (A)
  QV1008    658-665  (A)
  QV1009    666-676  (A)
  QV1010U   677-677 
  QV1010N   678-679 
  QV1011    680-680 
  QV1012    681-689  (A)
  QV1013U   690-690 
  QV1013N   691-692 
  QV1015    693-694 
  QV1016    695-704  (A)
  QV1017    705-707 
  QV1018    708-716  (A)
  QV1019    717-717 
  QV1020U   718-718 
  QV1020N   719-720 
  QV1021U   721-721 
  QV1021N   722-723 
  QV1022A   724-724 
  QV1022B   725-725 
  QV1022C   726-726 
  QV1022D   727-727 
  QV1022E   728-728 
  QV1022F   729-729 
  QV1022G   730-730 
  QV1022X   731-731 
  QV1022Y   732-732 
  QV1023    733-733 
  QV1024U   734-734 
  QV1024N   735-736 
  QV1025    737-737 
  QV1026    738-739 
  QV1027U   740-740 
  QV1027N   741-742 
  QV1028    743-753  (A)
  QV1029    754-754 
  QV1030    755-767  (A)
  QV1031    768-768 
  QV1032    769-770 
  QV1033    771-780  (A)
  QV1034    781-788  (A)
  QV1035    789-789 
  QV1036U   790-790 
  QV1036N   791-792 
  QV1037A   793-793 
  QV1037B   794-794 
  QV1037C   795-795 
  QV1037D   796-796 
  QV1037E   797-797 
  QV1037F   798-798 
  QV1037G   799-799 
  QV1037X   800-800 
  QV1037Y   801-801 
  QV1038    802-802 
  QV1039U   803-803 
  QV1039N   804-805 
  QV1040    806-806 
  QV1041    807-808 
  QV1042    809-819  (A)
  QV1043    820-825 
  QV1044    826-831  (A)
  QV1045    832-832 
  QV1046    833-833 
  QV1047U   834-834 
  QV1047N   835-836 
  QVH146H   837-838 
  QVH146M   839-840 
  QVH101    841-842 
  QVH102    843-844 
  QVH103    845-845 
  QVH104    846-848 
  QVH106    849-849 
  QVH107    850-850 
  QVH108    851-857  (A)
  QVH109    858-859 
  QVH110    860-860 
  QVH111    861-862 
  QVH112    863-863 
  QVH113    864-865 
  QVH114    866-866 
  QVH115    867-867 
  QVH116    868-869 
  QVH117    870-870 
  QVH118A   871-872 
  QVH118B   873-874 
  QVH118C   875-876 
  QVH118D   877-878 
  QVH118E   879-880 
  QVH118F   881-882 
  QVH118G   883-884 
  QVH121A   885-885 
  QVH121B   886-886 
  QVH121C   887-887 
  QVH121D   888-888 
  QVH121E   889-889 
  QVH121F   890-890 
  QVH121G   891-891 
  QVH121H   892-892 
  QVH121I   893-893 
  QVH121J   894-894 
  QVH121K   895-895 
  QVH121L   896-896 
  QVH121M   897-897 
  QVH121N   898-898 
  QVH121O   899-899 
  QVH121P   900-900 
  QVH121Q   901-901 
  QVH121R   902-902 
  QVH122A   903-903 
  QVH122B   904-904 
  QVH122C   905-905 
  QVH122D   906-906 
  QVH122E   907-907 
  QVH122F   908-908 
  QVH122G   909-909 
  QVH122H   910-910 
  QVH122I   911-911 
  QVH122J   912-912 
  QVH142    913-914 
  QVH143    915-916 
  QVH144    917-918 
  QCD06     919-920 
  QCD07     921-922 
  QCD08C_A  923-926  (A)
  QCD08C_B  927-930  (A)
  QCD08C_C  931-934  (A)
  QCD08C_D  935-938  (A)
  QCD09     939-939 
  QCD10     940-940 
  QCD10A    941-941 
  QCD11     942-942 
  QCD12AC   943-946  (A)
  QCD12BC   947-950  (A)
  QCD13C    951-951 
  QCD13D    952-952 
  QCD13E1   953-953 
  QCD13E2   954-954 
  QCD13E3   955-955 
  QCD14     956-956 
 .
VARIABLE LABELS
   QHCLUST  "Cluster number"
  /QHNUMBER "Household number"
  /QLINE    "Line number of individual questionnaire"
  /QREGION  "Region of residence"
  /QDIST    "District"
  /QTYPE    "Type of place of residence"
  /QQTYPE   "Type of questionnaire"
  /QINTD    "Day of interview"
  /QINTM    "Month of interview"
  /QINTY    "Year of interview"
  /QINTNUM  "Interviewer number"
  /QRESULT  "Result of individual interview"
  /QVISITS  "Total number of visits"
  /QLANGQ   "Language of questionnaire"
  /QLANGI   "Language of interview"
  /QLANGR   "Language of respondent"
  /QTRANS   "Translator used"
  /QSUPERV  "Supervisor number"
  /QFEDIT   "Field editor number"
  /QKEYER   "Data entry clerk"
  /QINTC    "Date of interview (CMC)"
  /QINTCD   "Date of interview Century Day Code (CDC)"
  /QWEIGHT  "Sample weight (6 decimals)"
  /QV101$1  "Line number"
  /QV101$2  "Line number"
  /QV101$3  "Line number"
  /QV101$4  "Line number"
  /QV101$5  "Line number"
  /QV101$6  "Line number"
  /QV101$7  "Line number"
  /QV103$1  "Sex"
  /QV103$2  "Sex"
  /QV103$3  "Sex"
  /QV103$4  "Sex"
  /QV103$5  "Sex"
  /QV103$6  "Sex"
  /QV103$7  "Sex"
  /QV104$1  "Age of respondent"
  /QV104$2  "Age of respondent"
  /QV104$3  "Age of respondent"
  /QV104$4  "Age of respondent"
  /QV104$5  "Age of respondent"
  /QV104$6  "Age of respondent"
  /QV104$7  "Age of respondent"
  /QV105$1  "Relationship to deceased"
  /QV105$2  "Relationship to deceased"
  /QV105$3  "Relationship to deceased"
  /QV105$4  "Relationship to deceased"
  /QV105$5  "Relationship to deceased"
  /QV105$6  "Relationship to deceased"
  /QV105$7  "Relationship to deceased"
  /QV106$1  "Highest education passed"
  /QV106$2  "Highest education passed"
  /QV106$3  "Highest education passed"
  /QV106$4  "Highest education passed"
  /QV106$5  "Highest education passed"
  /QV106$6  "Highest education passed"
  /QV106$7  "Highest education passed"
  /QV107$1  "Present when first fell ill"
  /QV107$2  "Present when first fell ill"
  /QV107$3  "Present when first fell ill"
  /QV107$4  "Present when first fell ill"
  /QV107$5  "Present when first fell ill"
  /QV107$6  "Present when first fell ill"
  /QV107$7  "Present when first fell ill"
  /QV108$1  "Present when taken to hospital"
  /QV108$2  "Present when taken to hospital"
  /QV108$3  "Present when taken to hospital"
  /QV108$4  "Present when taken to hospital"
  /QV108$5  "Present when taken to hospital"
  /QV108$6  "Present when taken to hospital"
  /QV108$7  "Present when taken to hospital"
  /QV109$1  "Present when died"
  /QV109$2  "Present when died"
  /QV109$3  "Present when died"
  /QV109$4  "Present when died"
  /QV109$5  "Present when died"
  /QV109$6  "Present when died"
  /QV109$7  "Present when died"
  /QV110$1  "Main respondent"
  /QV110$2  "Main respondent"
  /QV110$3  "Main respondent"
  /QV110$4  "Main respondent"
  /QV110$5  "Main respondent"
  /QV110$6  "Main respondent"
  /QV110$7  "Main respondent"
  /QV201H   "Start of interview (hour)"
  /QV201M   "Start of interview (minutes)"
  /QV204D   "Day of death"
  /QV204M   "Month of death"
  /QV204Y   "Year of death"
  /QV204BD  "Day of birth"
  /QV204BM  "Month of birth"
  /QV204BY  "Year of birth"
  /QV205    "Age at death"
  /QV206    "Was usual member or was here temporarily"
  /QV207    "Ever attended school"
  /QV208    "Highest class completed"
  /QV209    "Working for wages or salary when she died"
  /QV210    "Occupation"
  /QV211    "Mother tongue"
  /QV212    "Marital status"
  /QV214    "Age of husband at the time of her death"
  /QV215    "Husband ever attended school"
  /QV216    "Husband highest class completed"
  /QV217    "Husband's occupation"
  /QV217A   "Death related to complications of pregnancy or childbirth"
  /QVELIG   "VA eligibility"
  /QV204BC  "Date of birth (CMC)"
  /QV204BF  "Date flag for Q204BC"
  /QV204C   "Date of death (CMC)"
  /QV204F   "Date flag for Q204C"
  /QV204CD  "Date of death Century Day Code (CDC)"
  /QV204DI  "Imputed day of death"
  /QV301    "Ever given birth"
  /QV302    "Live children she had"
  /QV303A   "Living children still alive"
  /QV303B   "Boys still alive"
  /QV303C   "Girls still alive"
  /QV304    "Any abortion,miscarriage,stillbirth"
  /QV305A   "Number of abortions"
  /QV305B   "Number of stillbirths"
  /QV305C   "Number of miscarriages"
  /QV305D   "Number of pregnancy losses"
  /QV307    "Ever had a caesarean section operation"
  /QV307A   "Number of caesarean sections"
  /QV308    "Had a pregnancy during last 3 years of her life"
  /QV309U   "How long before her death the last pregnancy end (units)"
  /QV309N   "How long before her death the last pregnancy end (number)"
  /QV310    "Outcome of last pregnancy"
  /QV311    "Last born still alive"
  /QV312    "Age of child"
  /QV313U   "How old was the child when died (units)"
  /QV313N   "How old was the child when died (number)"
  /QV314U   "How long after last birth/delivery/miscarriage/abortion did she die (units)"
  /QV314N   "How long after last birth/delivery/miscarriage/abortion did she die (number)"
  /QV315    "Was pregnant when she died"
  /QV316    "Months of pregnant when she died"
  /QV318    "Died before labour pains/before birth or during abortion or miscarriage"
  /QV321    "Died within 40 days of delivery, abortion or miscarriage"
  /QV501    "Place of death"
  /QV502    "Hospital name"
  /QV503    "Anyone at the hospital/clinic tell you why she died"
  /QV504    "Reason given by the hospital/clinic"
  /QV505    "Main cause of her death"
  /QV506A   "High blood pressure"
  /QV506B   "Sugar/diabetes"
  /QV506C   "Epilepsy"
  /QV506D   "TB"
  /QV506E   "Hearth disease"
  /QV506F   "Blood disease"
  /QV506G   "Asthma"
  /QV506H   "Severe anemia"
  /QV506I   "Jaundice"
  /QV506J   "Hepatitis"
  /QV506K   "Hiv/Aids"
  /QV506L   "Cancer"
  /QV506X   "Other disease"
  /QV507    "Ever hospitalized"
  /QV508U   "How long before her death the last pregnancy end (units)"
  /QV508N   "How long before her death the last pregnancy end (number)"
  /QV509    "Reason of last hospitalization"
  /QV510    "Had any operation before she died"
  /QV510A   "Operation type"
  /QV511    "Had fever"
  /QV511AU  "Fever duration  (units)"
  /QV511AN  "Fever duration (number)"
  /QV511B   "Was the fever continuous or on and off"
  /QV512    "Was she breathless doing light work"
  /QV512A   "Was she breathless when was lying down"
  /QV513    "Had rapid heart beat (palpitations)"
  /QV514    "Had wheezing"
  /QV515    "Had cough"
  /QV515AU  "Duration of cough (units)"
  /QV515AN  "Duration of cough (number)"
  /QV515B   "Cough produce sputum"
  /QV515C   "Cough blood"
  /QV516    "Had chest pain"
  /QV516AU  "Duration of chest pain (units)"
  /QV516AN  "Duration of chest pain (number)"
  /QV516B   "Chest pain severity"
  /QV516C   "Chest pain started suddenly or gradually"
  /QV516D   "Pain at or near the center of the chest"
  /QV517    "Had diarrhea (loose motions)"
  /QV517A   "Times had loose motions"
  /QV517B   "Had blood in the stools"
  /QV518    "Had poor appetite or loss of appetite"
  /QV518AU  "Duration of appetite lost (units)"
  /QV518AN  "Duration of appetite lost (number)"
  /QV520    "Had difficulty in swallowing"
  /QV520A   "Had pain in swallowing"
  /QV521    "Had headache"
  /QV521AU  "Duration of headache (units)"
  /QV521AN  "Duration of headache (number)"
  /QV522    "Had blood in urine"
  /QV522AU  "Duration passed blood in urine (units)"
  /QV522AN  "Duration passed blood in urine (number)"
  /QV523    "Had pain while urinating"
  /QV523AU  "Duration of pain when urinating (units)"
  /QV523AN  "Duration of pain when urinating (number)"
  /QV524    "Unabled to pass urine"
  /QV525    "Urinated many times in a day"
  /QV526    "Had any type of pain anywhere in the body"
  /QV527    "Had abdominal pain"
  /QV527AU  "Duration of abdominal pain (units)"
  /QV527AN  "Duration of abdominal pain (number)"
  /QV527B   "Abdominal pain severity"
  /QV527C   "Abdominal pain location"
  /QV528    "Had abdominal distension"
  /QV528AU  "Duration of abdomen distended (units)"
  /QV528AN  "Duration of abdomen distended (number)"
  /QV528B   "Distension come rapidly or slowly"
  /QV529    "Had mass in her abdomen"
  /QV530    "Had vomiting"
  /QV530AU  "Duration of vomiting (units)"
  /QV530AN  "Duration of vomiting (number)"
  /QV530B   "Vomited blood"
  /QV531    "Became mentally confused"
  /QV532    "Lost consciousness"
  /QV532AU  "Duration of remained unconscious (units)"
  /QV532AN  "Duration of remained unconscious (number)"
  /QV532B   "Became unconscious suddenly or gradually"
  /QV533    "Became paralyze"
  /QV533AU  "Duration of paralysis (units)"
  /QV533AN  "Duration of paralysis (number)"
  /QV533B   "Paralysis on one side or both sides of body"
  /QV534    "Had stiffness in her whole body"
  /QV535    "Had neck pain"
  /QV536    "Had convulsions"
  /QV536AU  "Duration of convulsions (units)"
  /QV536AN  "Duration of convulsions (number)"
  /QV536B   "Times a day had fits"
  /QV537    "Had ulcer or swelling/lump in the breast"
  /QV538    "Had vaginal bleeding"
  /QV538AU  "Duration of bleeding (units)"
  /QV538AN  "Duration of bleeding (number)"
  /QV538B   "Bleeding persist until she died"
  /QV539    "Had abnormal vaginal discharge"
  /QV540    "Had swelling on her ankles"
  /QV541    "Had swelling or puffiness on her hands"
  /QV541AU  "Duration of had swelling on her hands and/or face (units)"
  /QV541AN  "Duration of had swelling on her hands and/or face (number)"
  /QV542    "Lost weight"
  /QV543    "Had sores in her mouth"
  /QV544    "Had skin disease"
  /QV545    "Looked pale"
  /QV545A   "Had jaundice"
  /QV546    "Were eyes yellowish"
  /QV546AU  "Duration of had yellow eyes (units)"
  /QV546AN  "Duration of had yellow eyes (number)"
  /QV547    "Had blurred vision"
  /QV548    "Had difficulty in opening her mouth"
  /QV549    "Had difficulty in passing stools or constipation"
  /QV550    "Felt dizzy"
  /QV551    "Had general weakness or fatigue"
  /QV551AU  "Duration of had weakness (units)"
  /QV551AN  "Duration of had weakness (number)"
  /QV551B   "Had light flashes before her eyes closed at night"
  /QV551C   "Complained of double vision"
  /QV552    "Had any ulcers on her body"
  /QV553$1  "Other symptoms"
  /QV553$2  "Other symptoms"
  /QV553$3  "Other symptoms"
  /QV553$4  "Other symptoms"
  /QV553$5  "Other symptoms"
  /QV553$6  "Other symptoms"
  /QV553$7  "Other symptoms"
  /QV554    "People though had an evil eye or shadow"
  /QV555    "Faith healer called or amulets given"
  /QV556    "Spiritual healing details"
  /QV602U   "How long before she died the fever start (units)"
  /QV602N   "How long before she died the fever start (number)"
  /QV602A   "When did the fever start"
  /QV602BU  "How long before/after childbirth, miscarriage or abortion the fever start (units)"
  /QV602BN  "How long before/after childbirth, miscarriage or abortion the fever start (number)"
  /QV603U   "How long did it last (units)"
  /QV603N   "How long did it last (number)"
  /QV604    "Fever high"
  /QV605    "Fever with chills"
  /QV606    "Prescribed antimalarial tablets for fever and chills"
  /QV607    "Colour changed during last illness"
  /QV607A   "What was the color"
  /QV608    "Vomiting during last illness"
  /QV608AU  "How long before she died the vomiting start (units)"
  /QV608AN  "How long before she died the vomiting start (number)"
  /QV608B   "Had severe body aches during fever"
  /QV609    "Ever vomited pure blood"
  /QV610    "Had any difficulty with urination"
  /QV610AA  "Unable to pass urine"
  /QV610AB  "Too frequent urination"
  /QV610AC  "Painful urination"
  /QV610AD  "Back pain with fever"
  /QV610AE  "Blood in urine"
  /QV610AX  "Other urination difficulty"
  /QV613    "Had convulsion with fever"
  /QV615U   "How long before she died the cough start (units)"
  /QV615N   "How long before she died the cough start (number)"
  /QV616    "Sputum when coughed"
  /QV617    "Blood in it"
  /QV617A   "How much blood did the sputum contain"
  /QV618    "Lost weight during illness"
  /QV620    "Was she short of breath"
  /QV620AU  "How long was short of breath (units)"
  /QV620AN  "How long was short of breath (number)"
  /QV622    "Kind of pain"
  /QV623    "Pain location"
  /QV624U   "How long before she died did the pain start (units)"
  /QV624N   "How long before she died did the pain start (number)"
  /QV625U   "How long did the pain last (units)"
  /QV625N   "How long did the pain last (number)"
  /QV625A   "Had pain in upper abdomen"
  /QV625B   "When did the pain start"
  /QV626    "Pain in abdomen"
  /QV627    "Any pain in the lower abdomen"
  /QV628    "Pain was accompanied by fever"
  /QV629    "Fever severity"
  /QV630    "Pain was accompanied by vomiting"
  /QV633    "Had a history of convulsions"
  /QV634    "Had convulsions in her last illness"
  /QV634AU  "How long before death had convulsions (units)"
  /QV634AN  "How long before death had convulsions (number)"
  /QV635    "Had high blood pressure"
  /QV636    "Had severe headache"
  /QV637    "Had change in her vision"
  /QV638    "State of consciousness"
  /QV638A   "Had history of convulsion or epilepsy"
  /QV638B   "Times had convulsions"
  /QV638D   "When did convulsions start"
  /QV638E   "Duration of convulsions"
  /QV638F   "Convulsions restricted to one part or the whole body"
  /QV640A   "Swelling in abdomen"
  /QV640B   "Swelling in face"
  /QV640C   "Swelling in legs and feet"
  /QV640D   "Swelling in whole body"
  /QV641U   "How long before she died she have this swelling (units)"
  /QV641N   "How long before she died she have this swelling (number)"
  /QV642U   "When did the swelling start in relation to delivery of the baby or abortion or miscarriage (units)"
  /QV642N   "When did the swelling start in relation to delivery of the baby or abortion or miscarriage (number)"
  /QV643    "Was she short of breath"
  /QV644    "Colour changed during last illness"
  /QV644A   "Had yellowness of skin of face"
  /QV645    "Had any urinary problem"
  /QV645AA  "Unabled to pass urine"
  /QV645AB  "Too frequent urination"
  /QV645AC  "Painful urination"
  /QV645AD  "Blood in urine"
  /QV645AX  "Other urinary problem"
  /QV702    "Did see anyone for antenatal care"
  /QV703    "Who did she see for antenatal care"
  /QV704    "Did she go because she had a problem or went for a check-up"
  /QV705    "What was the problem she went for"
  /QV706    "Month of pregnant at first health provider visit"
  /QV707    "Times saw a health provider"
  /QV708    "Referred to a specialist"
  /QV709    "Reason didn't sought care for ANC"
  /QV710    "During last pregnancy had an injection to prevent tetanus"
  /QV711    "During last pregnancy blood pressure was measured"
  /QV712    "Blood pressure"
  /QV713    "Prescribed medicines for blood pressure"
  /QV714    "Using family planning method before became pregnant"
  /QV715    "Wanted pregnancy"
  /QV716    "Tried to end the pregnancy"
  /QV717    "Action take to end the pregnancy"
  /QV718    "Went for help to end the pregnancy"
  /QV720    "Had a foul-smelling discharge after miscarriage/abortion"
  /QV721    "Had fever after miscarriage/abortion"
  /QV722    "Had abdominal distension after miscarriage/abortion"
  /QV726    "Had bleeding from vagina"
  /QV727    "Bleeding wet her clothes"
  /QV728    "Bleeding wet the bed"
  /QV729    "Was much blood as to wet the floor"
  /QV730    "Pain while bleeding"
  /QV731    "Bleeding contains clots"
  /QV732    "Examined internally during last pregnancy"
  /QV733    "Vaginal examination cause any bleeding"
  /QV734    "Bleeding persisted until she died"
  /QV802    "Had bleeding from vagina"
  /QV803    "Bleeding started before or after the birth/delivery"
  /QV804    "Pain while bleeding"
  /QV805    "Pain started before the labor pains"
  /QV806    "Place of delivery"
  /QV807    "Assistance at delivery"
  /QV808    "Any instrument used to assist delivery"
  /QV808A   "Death reason confirmation"
  /QV808B   "How was the delivery"
  /QV809    "Vagina was cut to make room"
  /QV810    "Tear in vagina after last delivery"
  /QV811    "Birth attendant examined vagina using hands or instruments"
  /QV812    "Water bag broken before the labor pains"
  /QV813    "Duration of labor"
  /QV814    "Given any drugs before or during labor"
  /QV815    "Drugs given"
  /QV816    "Had a lot of bleeding before delivery"
  /QV817    "Bleeding wet her clothes"
  /QV818    "Bleeding wet the bed"
  /QV819    "Was much blood as to wet the floor"
  /QV820    "Died before or after baby was born"
  /QV821    "Difficulty delivering the baby"
  /QV822    "Part of the baby came out first"
  /QV823    "Placenta came out"
  /QV824U   "How long after the baby came the placenta came out (units)"
  /QV824N   "How long after the baby came the placenta came out (number)"
  /QV825    "All the placenta came out"
  /QV826    "Had a lot of bleeding after delivery"
  /QV827    "Bleeding wet her clothes"
  /QV828    "Bleeding wet the bed"
  /QV829    "Was much blood as to wet the floor"
  /QV830    "Had a foul-smelling discharge after baby was born"
  /QV831    "Had a pain in legs after baby was born"
  /QV832    "Had fever after baby was born"
  /QV833U   "How long after delivery the fever started (units)"
  /QV833N   "How long after delivery the fever started (number)"
  /QV834    "Had any fits or rigors with the fever"
  /QV835    "Fits stopped after the baby was born"
  /QV836U   "Fever duration  (units)"
  /QV836N   "Fever duration (number)"
  /QV837    "Had fever when she died"
  /QV838    "Color of eyes yellow after the baby was born"
  /QV839    "Birth attendant examined vagina using hands or instruments"
  /QV840    "Received a blood transfusion"
  /QV841    "When got blood transfusion"
  /QV901    "Had serious accident or injury"
  /QV902    "Type of accident or injury"
  /QV903U   "How long before she died the accident/injury happened (units)"
  /QV903N   "How long before she died the accident/injury happened (number)"
  /QV904    "Hurt intentionally or was an accident"
  /QV905    "Was trying to commit suicide"
  /QV906    "Was the injury the main cause of death or contributed to the death"
  /QV1001U  "How long after having symptoms a serious problem was recognized (units)"
  /QV1001N  "How long after having symptoms a serious problem was recognized  (number)"
  /QV1002   "How serious the family perceived this complication or problem to be"
  /QV1003   "Family thought she could have died because of her problem"
  /QV1004   "Sought treatment for last illness"
  /QV1005   "Reasons didn't seek for treatment"
  /QV1006   "Who was involved in decision that should not go for treatment"
  /QV1007   "From whom received treatment"
  /QV1008   "Place of treatment"
  /QV1009   "Who was involved in decision that should go for treatment"
  /QV1010U  "How long after the problem was recognized it was decided to go for treatment (units)"
  /QV1010N  "How long after the problem was recognized it was decided to go for treatment (number)"
  /QV1011   "Tried to go immediately after decided to go for treatment"
  /QV1012   "Reasons didn't go immediately"
  /QV1013U  "Time between first recognition of the seriousness of symptoms and taking to hospital (units)"
  /QV1013N  "Time between first recognition of the seriousness of symptoms and taking to hospital (number)"
  /QV1015   "First place of treatment"
  /QV1016   "Who went with her to the first place for treatment"
  /QV1017   "Distance from home to health facility"
  /QV1018   "How she went to the first place of treatment"
  /QV1019   "Difficult to get transport to first place of treatment"
  /QV1020U  "Time to go to the first treatment place (units)"
  /QV1020N  "Time to go to the first treatment place (number)"
  /QV1021U  "Time waiting to be examined in the first hospital/clinic (units)"
  /QV1021N  "Time waiting to be examined in the first hospital/clinic (number)"
  /QV1022A  "Treatment: Injection in arm"
  /QV1022B  "Treatment: Injection in butt"
  /QV1022C  "Treatment: Drip"
  /QV1022D  "Treatment: Transfusion"
  /QV1022E  "Treatment: Operation"
  /QV1022F  "Treatment: Pills/Capsules"
  /QV1022G  "Treatment: Oxygen"
  /QV1022X  "Treatment: Other 1"
  /QV1022Y  "Treatment: Other 2"
  /QV1023   "Condition improved after treatment in first place"
  /QV1024U  "Time between she arrived in the hospital/clinic and the death (units)"
  /QV1024N  "Time between she arrived in the hospital/clinic and the death (number)"
  /QV1025   "First hospital/clinic referred to other hospital"
  /QV1026   "Referral place from first hospital/clinic"
  /QV1027U  "Time between she arrived in the hospital/clinic and was referred to the second hospital/clinic (units)"
  /QV1027N  "Time between she arrived in the hospital/clinic and was referred to the second hospital/clinic (number)"
  /QV1028   "Reasons for referral to the second place"
  /QV1029   "Went to the referred place"
  /QV1030   "Reasons didn't go to the referred place"
  /QV1031   "Went to anywhere else for treatment"
  /QV1032   "Last place of treatment"
  /QV1033   "Who went with her to the last place for treatment"
  /QV1034   "How she went to the last place of treatment"
  /QV1035   "Difficult to get transport for last place of treatment"
  /QV1036U  "Time waiting to be examined in the last hospital/clinic (units)"
  /QV1036N  "Time waiting to be examined in the last hospital/clinic (number)"
  /QV1037A  "Treatment: Injection in arm"
  /QV1037B  "Treatment: Injection in butt"
  /QV1037C  "Treatment: Drip"
  /QV1037D  "Treatment: Transfusion"
  /QV1037E  "Treatment: Operation"
  /QV1037F  "Treatment: Pills/Capsules"
  /QV1037G  "Treatment: Oxygen"
  /QV1037X  "Treatment: Other 1"
  /QV1037Y  "Treatment: Other 2"
  /QV1038   "Condition improved after treatment in last place"
  /QV1039U  "Time between she arrived in the last hospital/clinic and the death (units)"
  /QV1039N  "Time between she arrived in the last hospital/clinic and the death (number)"
  /QV1040   "Last hospital/clinic referred to other hospital"
  /QV1041   "Referral place from last hospital/clinic"
  /QV1042   "Reasons for referral to another place"
  /QV1043   "Cost of treatment"
  /QV1044   "Funds source"
  /QV1045   "Died in hospital"
  /QV1046   "Place of death"
  /QV1047U  "Time between she died and they removed the body from the hospital/clinic (units)"
  /QV1047N  "Time between she died and they removed the body from the hospital/clinic (number)"
  /QVH146H  "End of interview (hour)"
  /QVH146M  "End of interview (minutes)"
  /QVH101   "Source of drinking water"
  /QVH102   "Source of water for cooking/handwashing"
  /QVH103   "Location of source for water"
  /QVH104   "Time to water and back (minutes)"
  /QVH106   "Water not available for at least a day"
  /QVH107   "Do anything to water to make safe to drink"
  /QVH108   "What do you usually do to make water safe to drink"
  /QVH109   "Type of toilet facility"
  /QVH110   "Share facility with other households"
  /QVH111   "Number of households sharing toilet"
  /QVH112   "Location of toilet facility"
  /QVH113   "Type of cooking fuel"
  /QVH114   "Location of cooking"
  /QVH115   "Household has separate room used as kitchen"
  /QVH116   "Number of rooms used for sleeping"
  /QVH117   "Owns livestock, herds, farm animals, poultry"
  /QVH118A  "Cows/bulls"
  /QVH118B  "Other cattle (buffalo)"
  /QVH118C  "Horses/donkeys/mules"
  /QVH118D  "Goats"
  /QVH118E  "Sheep"
  /QVH118F  "Camels"
  /QVH118G  "Chickens/poultry"
  /QVH121A  "Electricity"
  /QVH121B  "Radio"
  /QVH121C  "Television"
  /QVH121D  "Non-mobile telephone"
  /QVH121E  "Refrigerator"
  /QVH121F  "Almirah/Cabinet"
  /QVH121G  "Chair"
  /QVH121H  "Room cooler"
  /QVH121I  "Airconditioner"
  /QVH121J  "Washing machine"
  /QVH121K  "Water pump"
  /QVH121L  "Bed"
  /QVH121M  "Clock"
  /QVH121N  "Sofa"
  /QVH121O  "Camera"
  /QVH121P  "Sewing machine"
  /QVH121Q  "Computer"
  /QVH121R  "Internet connection"
  /QVH122A  "Watch"
  /QVH122B  "Mobile telephone"
  /QVH122C  "Bicycle"
  /QVH122D  "Motorcycle or scooter"
  /QVH122E  "Animal-drawn cart"
  /QVH122F  "Car or Truck"
  /QVH122G  "Tractor"
  /QVH122H  "Boat with a motor"
  /QVH122I  "Boat without motor"
  /QVH122J  "Rickshaw/chingchi"
  /QVH142   "Main floor material"
  /QVH143   "Main roof material"
  /QVH144   "Main wall material"
  /QCD06    "Age at death"
  /QCD07    "Reviewer's code"
  /QCD08C_A "A ICD Code"
  /QCD08C_B "B ICD Code"
  /QCD08C_C "C ICD Code"
  /QCD08C_D "D ICD Code"
  /QCD09    "Was surgery performed within the last 4 weeks?"
  /QCD10    "Was the deceased pregnant?"
  /QCD10A   "If Yes, than"
  /QCD11    "Did the pregnancy contribute to the death?"
  /QCD12AC  "Tentative underlying cause of death - Code"
  /QCD12BC  "Final underlying cause of death - Code"
  /QCD13C   "Reviewer's decision on the category of death (see definition) Choose one:"
  /QCD13D   "Timing of death in relation to pregnancy, delivery or postpartum (choose one):"
  /QCD13E1  "Delay in seeking treatment (address all three delays):FIRST DELAY"
  /QCD13E2  "SECOND DELAY"
  /QCD13E3  "THIRD DELAY"
  /QCD14    "Reviewer's assessment of quality of information in the VA questionnaire. Please circle one."
 .
MISSING VALUE
   QV104$1  (99)
  /QV104$2  (99)
  /QV104$3  (99)
  /QV104$4  (99)
  /QV104$5  (99)
  /QV104$6  (99)
  /QV104$7  (99)
  /QV105$1  (99)
  /QV105$2  (99)
  /QV105$3  (99)
  /QV105$4  (99)
  /QV105$5  (99)
  /QV105$6  (99)
  /QV105$7  (99)
  /QV106$1  (99)
  /QV106$2  (99)
  /QV106$3  (99)
  /QV106$4  (99)
  /QV106$5  (99)
  /QV106$6  (99)
  /QV106$7  (99)
  /QV107$1  (9)
  /QV107$2  (9)
  /QV107$3  (9)
  /QV107$4  (9)
  /QV107$5  (9)
  /QV107$6  (9)
  /QV107$7  (9)
  /QV108$1  (9)
  /QV108$2  (9)
  /QV108$3  (9)
  /QV108$4  (9)
  /QV108$5  (9)
  /QV108$6  (9)
  /QV108$7  (9)
  /QV109$1  (9)
  /QV109$2  (9)
  /QV109$3  (9)
  /QV109$4  (9)
  /QV109$5  (9)
  /QV109$6  (9)
  /QV109$7  (9)
  /QV201H   (99)
  /QV201M   (99)
  /QV204BD  (99)
  /QV204BM  (99)
  /QV204BY  (9998)
  /QV206    (9)
  /QV207    (9)
  /QV208    (99)
  /QV209    (9)
  /QV210    (99)
  /QV211    (99)
  /QV212    (9)
  /QV214    (99)
  /QV215    (9)
  /QV216    (99)
  /QV217    (99)
  /QV217A   (9)
  /QV301    (9)
  /QV304    (9)
  /QV307    (9)
  /QV307A   (9)
  /QV308    (9)
  /QV309N   (99)
  /QV310    (9)
  /QV311    (9)
  /QV312    (99)
  /QV313N   (99)
  /QV314N   (99)
  /QV315    (9)
  /QV316    (99)
  /QV318    (9)
  /QV321    (9)
  /QV501    (9)
  /QV503    (9)
  /QV506A   (9)
  /QV506B   (9)
  /QV506C   (9)
  /QV506D   (9)
  /QV506E   (9)
  /QV506F   (9)
  /QV506G   (9)
  /QV506H   (9)
  /QV506I   (9)
  /QV506J   (9)
  /QV506K   (9)
  /QV506L   (9)
  /QV506X   (9)
  /QV507    (9)
  /QV508N   (99)
  /QV510    (9)
  /QV511    (9)
  /QV511AN  (99)
  /QV511B   (9)
  /QV512    (9)
  /QV512A   (9)
  /QV513    (9)
  /QV514    (9)
  /QV515    (9)
  /QV515AN  (99)
  /QV515B   (9)
  /QV515C   (9)
  /QV516    (9)
  /QV516AN  (99)
  /QV516B   (9)
  /QV516C   (9)
  /QV516D   (9)
  /QV517    (9)
  /QV517A   (99)
  /QV517B   (9)
  /QV518    (9)
  /QV518AN  (99)
  /QV520    (9)
  /QV520A   (9)
  /QV521    (9)
  /QV521AN  (99)
  /QV522    (9)
  /QV522AN  (99)
  /QV523    (9)
  /QV523AN  (99)
  /QV524    (9)
  /QV525    (9)
  /QV526    (9)
  /QV527    (9)
  /QV527AN  (99)
  /QV527B   (9)
  /QV527C   (9)
  /QV528    (9)
  /QV528AN  (99)
  /QV528B   (9)
  /QV529    (9)
  /QV530    (9)
  /QV530AN  (99)
  /QV530B   (9)
  /QV531    (9)
  /QV532    (9)
  /QV532AN  (99)
  /QV532B   (9)
  /QV533    (9)
  /QV533AN  (99)
  /QV533B   (9)
  /QV534    (9)
  /QV535    (9)
  /QV536    (9)
  /QV536AN  (99)
  /QV536B   (99)
  /QV537    (9)
  /QV538    (9)
  /QV538AN  (99)
  /QV538B   (9)
  /QV539    (9)
  /QV540    (9)
  /QV541    (9)
  /QV541AN  (99)
  /QV542    (9)
  /QV543    (9)
  /QV544    (9)
  /QV545    (9)
  /QV545A   (9)
  /QV546    (9)
  /QV546AN  (99)
  /QV547    (9)
  /QV548    (9)
  /QV549    (9)
  /QV550    (9)
  /QV551    (9)
  /QV551AN  (99)
  /QV551B   (9)
  /QV551C   (9)
  /QV552    (9)
  /QV554    (9)
  /QV555    (9)
  /QV602N   (99)
  /QV602A   (9)
  /QV602BN  (99)
  /QV603N   (99)
  /QV604    (9)
  /QV605    (9)
  /QV606    (9)
  /QV607    (9)
  /QV607A   (9)
  /QV608    (9)
  /QV608AN  (99)
  /QV608B   (9)
  /QV609    (9)
  /QV610    (9)
  /QV610AA  (9)
  /QV610AB  (9)
  /QV610AC  (9)
  /QV610AD  (9)
  /QV610AE  (9)
  /QV610AX  (9)
  /QV613    (9)
  /QV615N   (99)
  /QV616    (9)
  /QV617    (9)
  /QV617A   (9)
  /QV618    (9)
  /QV620    (9)
  /QV620AN  (99)
  /QV622    (9)
  /QV624N   (99)
  /QV625N   (99)
  /QV625A   (9)
  /QV625B   (9)
  /QV627    (9)
  /QV628    (9)
  /QV629    (9)
  /QV630    (9)
  /QV633    (9)
  /QV634    (9)
  /QV634AN  (99)
  /QV635    (9)
  /QV636    (9)
  /QV637    (9)
  /QV638A   (9)
  /QV638B   (99)
  /QV638D   (9)
  /QV638E   (9)
  /QV638F   (9)
  /QV640A   (9)
  /QV640B   (9)
  /QV640C   (9)
  /QV640D   (9)
  /QV641N   (99)
  /QV642N   (99)
  /QV643    (9)
  /QV644    (9)
  /QV644A   (9)
  /QV645    (9)
  /QV645AA  (9)
  /QV645AB  (9)
  /QV645AC  (9)
  /QV645AD  (9)
  /QV645AX  (9)
  /QV702    (9)
  /QV704    (9)
  /QV706    (99)
  /QV707    (99)
  /QV708    (9)
  /QV710    (9)
  /QV711    (9)
  /QV712    (9)
  /QV713    (9)
  /QV714    (9)
  /QV715    (9)
  /QV716    (9)
  /QV717    (9)
  /QV718    (99)
  /QV720    (9)
  /QV721    (9)
  /QV722    (9)
  /QV726    (9)
  /QV727    (9)
  /QV728    (9)
  /QV729    (9)
  /QV730    (9)
  /QV731    (9)
  /QV732    (9)
  /QV733    (9)
  /QV734    (9)
  /QV802    (9)
  /QV803    (9)
  /QV804    (9)
  /QV805    (9)
  /QV806    (99)
  /QV807    (99)
  /QV808    (9)
  /QV808B   (9)
  /QV809    (9)
  /QV810    (9)
  /QV811    (9)
  /QV812    (9)
  /QV813    (99)
  /QV814    (9)
  /QV815    (9)
  /QV816    (9)
  /QV817    (9)
  /QV818    (9)
  /QV819    (9)
  /QV820    (9)
  /QV821    (9)
  /QV822    (9)
  /QV823    (9)
  /QV824N   (99)
  /QV825    (9)
  /QV826    (9)
  /QV827    (9)
  /QV828    (9)
  /QV829    (9)
  /QV830    (9)
  /QV831    (9)
  /QV832    (9)
  /QV833N   (99)
  /QV834    (9)
  /QV835    (9)
  /QV836N   (99)
  /QV837    (9)
  /QV838    (9)
  /QV839    (9)
  /QV840    (9)
  /QV841    (9)
  /QV901    (9)
  /QV902    (99)
  /QV903N   (99)
  /QV904    (9)
  /QV905    (9)
  /QV906    (9)
  /QV1001N  (99)
  /QV1002   (9)
  /QV1003   (9)
  /QV1004   (9)
  /QV1010N  (99)
  /QV1011   (9)
  /QV1013N  (99)
  /QV1015   (99)
  /QV1017   (999)
  /QV1019   (9)
  /QV1020N  (99)
  /QV1021N  (99)
  /QV1022A  (9)
  /QV1022B  (9)
  /QV1022C  (9)
  /QV1022D  (9)
  /QV1022E  (9)
  /QV1022F  (9)
  /QV1022G  (9)
  /QV1022X  (9)
  /QV1022Y  (9)
  /QV1023   (9)
  /QV1024N  (99)
  /QV1025   (9)
  /QV1026   (99)
  /QV1027N  (99)
  /QV1029   (9)
  /QV1031   (9)
  /QV1032   (99)
  /QV1035   (9)
  /QV1036N  (99)
  /QV1037A  (9)
  /QV1037B  (9)
  /QV1037C  (9)
  /QV1037D  (9)
  /QV1037E  (9)
  /QV1037F  (9)
  /QV1037G  (9)
  /QV1037X  (9)
  /QV1037Y  (9)
  /QV1038   (9)
  /QV1039N  (99)
  /QV1040   (9)
  /QV1041   (99)
  /QV1043   (999999)
  /QV1045   (9)
  /QV1046   (9)
  /QV1047N  (99)
  /QVH146H  (99)
  /QVH146M  (99)
  /QVH101   (99)
  /QVH102   (99)
  /QVH103   (9)
  /QVH104   (999)
  /QVH106   (9)
  /QVH107   (9)
  /QVH109   (99)
  /QVH110   (9)
  /QVH111   (99)
  /QVH112   (9)
  /QVH113   (99)
  /QVH114   (9)
  /QVH115   (9)
  /QVH116   (99)
  /QVH117   (9)
  /QVH118A  (99)
  /QVH118B  (99)
  /QVH118C  (99)
  /QVH118D  (99)
  /QVH118E  (99)
  /QVH118F  (99)
  /QVH118G  (99)
  /QVH121A  (9)
  /QVH121B  (9)
  /QVH121C  (9)
  /QVH121D  (9)
  /QVH121E  (9)
  /QVH121F  (9)
  /QVH121G  (9)
  /QVH121H  (9)
  /QVH121I  (9)
  /QVH121J  (9)
  /QVH121K  (9)
  /QVH121L  (9)
  /QVH121M  (9)
  /QVH121N  (9)
  /QVH121O  (9)
  /QVH121P  (9)
  /QVH121Q  (9)
  /QVH121R  (9)
  /QVH122A  (9)
  /QVH122B  (9)
  /QVH122C  (9)
  /QVH122D  (9)
  /QVH122E  (9)
  /QVH122F  (9)
  /QVH122G  (9)
  /QVH122H  (9)
  /QVH122I  (9)
  /QVH122J  (9)
  /QVH142   (99)
  /QVH143   (99)
  /QVH144   (99)
 .
VALUE LABELS
   QREGION 
      1 "Punjab"
      2 "Sindh"
      3 "KP"
      4 "Balochistan"
      5 "GB"
      6 "AJK"
  /QDIST   
    101 "Attock"
    102 "Bahawalnagar"
    103 "Bahawalpur"
    104 "Bhakkar"
    105 "Chakwal"
    106 "Chiniot"
    107 "Dera Ghazi Khan"
    108 "Faisalabad"
    109 "Gujranwala"
    110 "Gujrat"
    111 "Hafizabad"
    112 "Jhang"
    113 "Jhelum"
    114 "Kasur"
    115 "Khanewal"
    116 "Khushab"
    117 "Lahore"
    118 "Layyah"
    119 "Lodhran"
    120 "Mandi Bahauddin"
    121 "Mianwali"
    122 "Multan"
    123 "Muzaffargarh"
    124 "Nankana Sahib"
    125 "Narowal"
    126 "Okara"
    127 "Pakpattan"
    128 "Rahim Yar Khan"
    129 "Rajanpur"
    130 "Rawalpindi"
    131 "Sahiwal"
    132 "Sargodha"
    133 "Sheikhupura"
    134 "Sialkot"
    135 "Toba Tek Singh"
    136 "Vehari"
    201 "Badin"
    202 "Dadu"
    203 "Ghotki"
    204 "Hyderabad"
    205 "Jacobabad"
    206 "Jamshoro"
    207 "Karachi Central"
    208 "Karachi East"
    210 "Karachi South"
    211 "Karachi West"
    212 "Kashmore"
    213 "Khairpur"
    214 "Larkana"
    215 "Matiari"
    216 "Mirpur Khas"
    217 "Naushahro Feroze"
    218 "Sanghar"
    219 "Shahdad Kot"
    220 "Nawabshah/Shaheed Benazir Abad"
    221 "Shikarpur"
    222 "Sukkur"
    223 "Tando Alla Yar"
    224 "Tando Muhammad Khan"
    225 "Tharparkar"
    226 "Thatta"
    227 "Umer Kot"
    228 "Korangi"
    229 "Malair"
    230 "Sujawal"
    301 "Abbottabad"
    302 "Bannu"
    303 "Batagram"
    304 "Buner"
    305 "Charsadda"
    306 "Chitral"
    307 "D. I. Khan"
    308 "Hangu"
    309 "Haripur"
    310 "Karak"
    311 "Kohat"
    312 "Kohistan"
    313 "Lakki Marwat"
    314 "Lower Dir"
    315 "Malakand Protected Area"
    316 "Mansehra"
    317 "Mardan"
    318 "Nowshera"
    319 "Peshawar"
    320 "Shangla"
    321 "Swabi"
    322 "Swat"
    323 "Tank"
    324 "Tor Ghar"
    325 "Upper Dir"
    401 "Awaran"
    402 "Barkhan"
    403 "Bolan/Kachhi"
    404 "Chagai"
    405 "Dera Bugti"
    406 "Gawadar"
    407 "Harnai"
    408 "Jaffarabad"
    409 "Jhal Magsi"
    410 "Kalat"
    411 "Kech/Turbat"
    412 "Kharan"
    413 "Khuzdar"
    414 "Killa Abdullah"
    415 "Killa Saifullah"
    416 "Kohlu"
    417 "Lasbela"
    418 "Loralai"
    419 "Mastung"
    420 "Musakhel"
    421 "Nasirabad/Tamboo"
    422 "Nushki"
    423 "Panjgur"
    424 "Pishin"
    425 "Quetta"
    426 "Sherani"
    427 "Sibi"
    428 "Washuk"
    429 "Zhob"
    430 "Ziarat"
    432 "Sohbat Pur"
    501 "Astore"
    502 "Baltistan"
    503 "Diamir"
    504 "Ghanche"
    505 "Ghizer"
    506 "Gilgit"
    507 "Nagar"
    508 "Kharmang"
    509 "Hunza"
    510 "Shigar"
    601 "Islamabad"
    701 "Bajour"
    702 "Khyber"
    703 "Kurram"
    704 "Mohmand"
    705 "North Waziristan"
    706 "Orakzai"
    707 "South Waziristan"
    801 "Bagh"
    802 "Bhimber"
    803 "Hattian Bala"
    804 "Haveli"
    805 "Kotli"
    806 "Mirpur"
    807 "Muzaffarabad"
    808 "Neelum"
    809 "Poonch"
    810 "Sudhonti"
  /QTYPE   
      1 "Urban"
      2 "Rural"
  /QQTYPE  
      1 "Verbal Autopsy"
      2 "Female"
  /QRESULT 
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
  /QLANGQ  
      1 "English"
      2 "Urdu"
      3 "Sindhi"
      4 "Punjabi"
      5 "Sariaki"
      6 "Baluchi"
      7 "Pushto"
      8 "Other"
  /QLANGI  
      1 "English"
      2 "Urdu"
      3 "Sindhi"
      4 "Punjabi"
      5 "Sariaki"
      6 "Baluchi"
      7 "Pushto"
      8 "Other"
  /QLANGR  
      1 "English"
      2 "Urdu"
      3 "Sindhi"
      4 "Punjabi"
      5 "Sariaki"
      6 "Baluchi"
      7 "Pushto"
      8 "Other"
  /QTRANS  
      1 "Yes"
      2 "No"
  /QV101$1 
      0 "No more respondents"
  /QV101$2 
      0 "No more respondents"
  /QV101$3 
      0 "No more respondents"
  /QV101$4 
      0 "No more respondents"
  /QV101$5 
      0 "No more respondents"
  /QV101$6 
      0 "No more respondents"
  /QV101$7 
      0 "No more respondents"
  /QV103$1 
      1 "Male"
      2 "Female"
  /QV103$2 
      1 "Male"
      2 "Female"
  /QV103$3 
      1 "Male"
      2 "Female"
  /QV103$4 
      1 "Male"
      2 "Female"
  /QV103$5 
      1 "Male"
      2 "Female"
  /QV103$6 
      1 "Male"
      2 "Female"
  /QV103$7 
      1 "Male"
      2 "Female"
  /QV104$1 
     95 "95+"
  /QV104$2 
     95 "95+"
  /QV104$3 
     95 "95+"
  /QV104$4 
     95 "95+"
  /QV104$5 
     95 "95+"
  /QV104$6 
     95 "95+"
  /QV104$7 
     95 "95+"
  /QV105$1 
      2 "Husband"
      3 "Son or daughter"
      4 "Son-in-law or daughter-in-law"
      5 "Grandchild"
      6 "Parent"
      7 "Parent-in-law"
      8 "Brother or sister"
      9 "Brother/sister-in-law"
     10 "Niece/Nephew"
     11 "Grand parent"
     12 "Aunts/uncle"
     13 "Other relative"
     14 "Adopted/foster/stepchild"
     15 "Not related"
     16 "Domestic servant"
  /QV105$2 
      2 "Husband"
      3 "Son or daughter"
      4 "Son-in-law or daughter-in-law"
      5 "Grandchild"
      6 "Parent"
      7 "Parent-in-law"
      8 "Brother or sister"
      9 "Brother/sister-in-law"
     10 "Niece/Nephew"
     11 "Grand parent"
     12 "Aunts/uncle"
     13 "Other relative"
     14 "Adopted/foster/stepchild"
     15 "Not related"
     16 "Domestic servant"
  /QV105$3 
      2 "Husband"
      3 "Son or daughter"
      4 "Son-in-law or daughter-in-law"
      5 "Grandchild"
      6 "Parent"
      7 "Parent-in-law"
      8 "Brother or sister"
      9 "Brother/sister-in-law"
     10 "Niece/Nephew"
     11 "Grand parent"
     12 "Aunts/uncle"
     13 "Other relative"
     14 "Adopted/foster/stepchild"
     15 "Not related"
     16 "Domestic servant"
  /QV105$4 
      2 "Husband"
      3 "Son or daughter"
      4 "Son-in-law or daughter-in-law"
      5 "Grandchild"
      6 "Parent"
      7 "Parent-in-law"
      8 "Brother or sister"
      9 "Brother/sister-in-law"
     10 "Niece/Nephew"
     11 "Grand parent"
     12 "Aunts/uncle"
     13 "Other relative"
     14 "Adopted/foster/stepchild"
     15 "Not related"
     16 "Domestic servant"
  /QV105$5 
      2 "Husband"
      3 "Son or daughter"
      4 "Son-in-law or daughter-in-law"
      5 "Grandchild"
      6 "Parent"
      7 "Parent-in-law"
      8 "Brother or sister"
      9 "Brother/sister-in-law"
     10 "Niece/Nephew"
     11 "Grand parent"
     12 "Aunts/uncle"
     13 "Other relative"
     14 "Adopted/foster/stepchild"
     15 "Not related"
     16 "Domestic servant"
  /QV105$6 
      2 "Husband"
      3 "Son or daughter"
      4 "Son-in-law or daughter-in-law"
      5 "Grandchild"
      6 "Parent"
      7 "Parent-in-law"
      8 "Brother or sister"
      9 "Brother/sister-in-law"
     10 "Niece/Nephew"
     11 "Grand parent"
     12 "Aunts/uncle"
     13 "Other relative"
     14 "Adopted/foster/stepchild"
     15 "Not related"
     16 "Domestic servant"
  /QV105$7 
      2 "Husband"
      3 "Son or daughter"
      4 "Son-in-law or daughter-in-law"
      5 "Grandchild"
      6 "Parent"
      7 "Parent-in-law"
      8 "Brother or sister"
      9 "Brother/sister-in-law"
     10 "Niece/Nephew"
     11 "Grand parent"
     12 "Aunts/uncle"
     13 "Other relative"
     14 "Adopted/foster/stepchild"
     15 "Not related"
     16 "Domestic servant"
  /QV106$1 
      0 "Less than class 1 completed"
     16 "Master's degree or mbbs, phd, mphil, bsc (4 years)"
     98 "Don't know"
  /QV106$2 
      0 "Less than class 1 completed"
     16 "Master's degree or mbbs, phd, mphil, bsc (4 years)"
     98 "Don't know"
  /QV106$3 
      0 "Less than class 1 completed"
     16 "Master's degree or mbbs, phd, mphil, bsc (4 years)"
     98 "Don't know"
  /QV106$4 
      0 "Less than class 1 completed"
     16 "Master's degree or mbbs, phd, mphil, bsc (4 years)"
     98 "Don't know"
  /QV106$5 
      0 "Less than class 1 completed"
     16 "Master's degree or mbbs, phd, mphil, bsc (4 years)"
     98 "Don't know"
  /QV106$6 
      0 "Less than class 1 completed"
     16 "Master's degree or mbbs, phd, mphil, bsc (4 years)"
     98 "Don't know"
  /QV106$7 
      0 "Less than class 1 completed"
     16 "Master's degree or mbbs, phd, mphil, bsc (4 years)"
     98 "Don't know"
  /QV107$1 
      1 "Yes"
      2 "No"
  /QV107$2 
      1 "Yes"
      2 "No"
  /QV107$3 
      1 "Yes"
      2 "No"
  /QV107$4 
      1 "Yes"
      2 "No"
  /QV107$5 
      1 "Yes"
      2 "No"
  /QV107$6 
      1 "Yes"
      2 "No"
  /QV107$7 
      1 "Yes"
      2 "No"
  /QV108$1 
      1 "Yes"
      2 "No"
      3 "Not taken"
  /QV108$2 
      1 "Yes"
      2 "No"
      3 "Not taken"
  /QV108$3 
      1 "Yes"
      2 "No"
      3 "Not taken"
  /QV108$4 
      1 "Yes"
      2 "No"
      3 "Not taken"
  /QV108$5 
      1 "Yes"
      2 "No"
      3 "Not taken"
  /QV108$6 
      1 "Yes"
      2 "No"
      3 "Not taken"
  /QV108$7 
      1 "Yes"
      2 "No"
      3 "Not taken"
  /QV109$1 
      1 "Yes"
      2 "No"
  /QV109$2 
      1 "Yes"
      2 "No"
  /QV109$3 
      1 "Yes"
      2 "No"
  /QV109$4 
      1 "Yes"
      2 "No"
  /QV109$5 
      1 "Yes"
      2 "No"
  /QV109$6 
      1 "Yes"
      2 "No"
  /QV109$7 
      1 "Yes"
      2 "No"
  /QV110$1 
      0 "Not eligible"
  /QV110$2 
      0 "Not eligible"
  /QV110$3 
      0 "Not eligible"
  /QV110$4 
      0 "Not eligible"
  /QV110$5 
      0 "Not eligible"
  /QV110$6 
      0 "Not eligible"
  /QV110$7 
      0 "Not eligible"
  /QV204D  
     98 "Don't know day"
  /QV204M  
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
  /QV204BD 
     98 "Don't know day"
  /QV204BM 
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     98 "Don't know month"
  /QV204BY 
   9998 "Don't know year"
  /QV205   
     95 "95 or more"
  /QV206   
      1 "Usual member"
      2 "Here temporarily"
  /QV207   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV208   
      0 "Less than class 1 completed"
     16 "Master's degree or mbbs, phd, mphil, bsc (4 years)"
     98 "Don't know"
  /QV209   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV210   
      1 "Commissioned armed forces officers"
      2 "Non-commissioned armed forces officers"
      3 "Armed forces occupations, other ranks"
     11 "Chief executives, senior officials and legislators"
     12 "Administrative and commercial managers"
     13 "Production and specialised services managers"
     14 "Hospitality, retail and other services managers"
     21 "Science and engineering professionals"
     22 "Health professionals"
     23 "Teaching professionals"
     24 "Business and administration professionals"
     25 "Information and communications technology professionals"
     26 "Legal, social and cultural professionals"
     31 "Science and engineering associate professionals"
     32 "Health associate professionals"
     33 "Business and administration associate professionals"
     34 "Legal, social, cultural and related associate professionals"
     35 "Information and communications technicians"
     41 "General and keyboard clerks"
     42 "Customer services clerks"
     43 "Numerical and material recording clerks"
     44 "Other clerical support workers"
     51 "Personal service workers"
     52 "Sales workers"
     53 "Personal care workers"
     54 "Protective services workers"
     61 "Market-oriented skilled agricultural workers"
     62 "Market-oriented skilled forestry, fishery and hunting workers"
     63 "Subsistence farmers, fishers, hunters and gatherers"
     71 "Building and related trades workers, excluding electricians"
     72 "Metal, machinery and related trades workers"
     73 "Handicraft and printing workers"
     74 "Electrical and electronic trades workers"
     75 "Food processing, wood working, garment and other craft and related trades workers"
     81 "Stationary plant and machine operators"
     82 "Assemblers"
     83 "Drivers and mobile plant operators"
     91 "Cleaners and helpers"
     92 "Agricultural, forestry and fishery labourers"
     93 "Labourers in mining, construction, manufacturing and transport"
     94 "Food preparation assistants"
     95 "Street and related sales and service workers"
     96 "Refuse workers and other elementary workers"
     97 "Other"
  /QV211   
      1 "Urdu"
      2 "Punjabi"
      3 "Sindhi"
      4 "Pushto"
      5 "Balochi"
      6 "English"
      7 "Barauhi"
      8 "Siraiki"
      9 "Hindko"
     10 "Kashmiri"
     11 "Shina"
     12 "Brushaski"
     13 "Wakhi"
     14 "Chitrali/ khwar"
     15 "Balti"
     16 "Pahari"
     17 "Potowari"
     18 "Marwari"
     19 "Farsi"
     96 "Other"
  /QV212   
      1 "Married"
      2 "Divorced"
      3 "Widowed"
      4 "Separated"
      5 "Never married"
  /QV214   
     95 "95+"
     98 "Don't know"
  /QV215   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV216   
      0 "Less than class 1 completed"
     16 "Master's degree or mbbs, phd, mphil, bsc (4 years)"
     98 "Don't know"
  /QV217   
      1 "Commissioned armed forces officers"
      2 "Non-commissioned armed forces officers"
      3 "Armed forces occupations, other ranks"
     11 "Chief executives, senior officials and legislators"
     12 "Administrative and commercial managers"
     13 "Production and specialised services managers"
     14 "Hospitality, retail and other services managers"
     21 "Science and engineering professionals"
     22 "Health professionals"
     23 "Teaching professionals"
     24 "Business and administration professionals"
     25 "Information and communications technology professionals"
     26 "Legal, social and cultural professionals"
     31 "Science and engineering associate professionals"
     32 "Health associate professionals"
     33 "Business and administration associate professionals"
     34 "Legal, social, cultural and related associate professionals"
     35 "Information and communications technicians"
     41 "General and keyboard clerks"
     42 "Customer services clerks"
     43 "Numerical and material recording clerks"
     44 "Other clerical support workers"
     51 "Personal service workers"
     52 "Sales workers"
     53 "Personal care workers"
     54 "Protective services workers"
     61 "Market-oriented skilled agricultural workers"
     62 "Market-oriented skilled forestry, fishery and hunting workers"
     63 "Subsistence farmers, fishers, hunters and gatherers"
     71 "Building and related trades workers, excluding electricians"
     72 "Metal, machinery and related trades workers"
     73 "Handicraft and printing workers"
     74 "Electrical and electronic trades workers"
     75 "Food processing, wood working, garment and other craft and related trades workers"
     81 "Stationary plant and machine operators"
     82 "Assemblers"
     83 "Drivers and mobile plant operators"
     91 "Cleaners and helpers"
     92 "Agricultural, forestry and fishery labourers"
     93 "Labourers in mining, construction, manufacturing and transport"
     94 "Food preparation assistants"
     95 "Street and related sales and service workers"
     96 "Refuse workers and other elementary workers"
     98 "Don't know"
     97 "Other"
  /QV217A  
      1 "Yes"
      2 "No"
  /QVELIG  
      1 "Eligible for VA"
      2 "Not eligible based on date of death"
      3 "Not eligible based on age of death"
  /QV204BF 
      0 "Ruled ineligible for survey"
      1 "Month and year"
      2 "Month and age -y imp"
      3 "Year and age - m imp"
      4 "Y & age - y ignored"
      5 "Year - a, m imp"
      6 "Age - y, m imp"
      7 "Month - a, y imp"
      8 "None - all imp"
  /QV204F  
      0 "Ruled ineligible for survey"
      1 "M of death and Y of death"
      2 "Y of death, Age of Death, Y of Birth, M of Birth - M of death imputed"
      3 "Y of death, Age of death, Year of birth - M of death imputed"
      4 "Y of death, Age of death, M of birth - M of death imputed"
      5 "Y of death, Age of death - M of death imputed"
      6 "Y of death - M of death imputed"
      7 "None - Y of death, M of death imputed"
      8 "Other"
  /QV301   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV302   
      0 "None"
  /QV303A  
      0 "None"
  /QV303B  
      0 "None"
  /QV303C  
      0 "None"
  /QV304   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV307   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV307A  
      8 "Don't know"
  /QV308   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV309U  
      1 "Days"
      2 "Months"
      3 "Years"
      9 "Special answers"
  /QV309N  
     98 "Don't know"
  /QV310   
      1 "Live birth"
      2 "Still birth"
      3 "Miscarriage"
      4 "Abortion"
      8 "Don't know"
  /QV311   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV313U  
      1 "Days"
      2 "Months"
      3 "Years"
      9 "Special answers"
  /QV313N  
     98 "Don't know"
  /QV314U  
      1 "Days"
      2 "Months"
      3 "Years"
      9 "Special answers"
  /QV314N  
     98 "Don't know"
  /QV315   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV316   
     98 "Don't know"
  /QV318   
      1 "Before labour pains began"
      2 "After labour pains began but before birth"
      3 "During delivery/abortion/miscarriage"
      4 "Before delivery of placenta"
      5 "During pregnancy"
      8 "Don't know"
  /QV321   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV501   
      1 "Hospital/clinic"
      2 "Husband's home"
      3 "Her parent's home"
      4 "In-transit"
      5 "Other"
      8 "Don't know"
  /QV502   
      6 "Hospital name"
  /QV503   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV504   
      6 "Reasons given by the hospital"
  /QV505   
      6 "Cause of death"
  /QV506A  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506B  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506C  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506D  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506E  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506F  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506G  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506H  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506I  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506J  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506K  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506L  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV506X  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV507   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV508U  
      1 "Days"
      2 "Months"
      3 "Years"
      9 "Special answers"
  /QV508N  
     98 "Don't know"
  /QV509   
      6 "Reason of last hospitalization"
  /QV510   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV510A  
      6 "Operation type"
  /QV511   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV511AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV511AN 
     98 "Don't know"
  /QV511B  
      1 "Continuous"
      2 "On and off"
      8 "Don't know"
  /QV512   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV512A  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV513   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV514   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV515   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV515AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV515AN 
     98 "Don't know"
  /QV515B  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV515C  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV516   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV516AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV516AN 
     98 "Don't know"
  /QV516B  
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /QV516C  
      1 "Suddenly"
      2 "Gradually"
      8 "Don't know"
  /QV516D  
      1 "Near sternum"
      2 "Somewhere else/all over"
      8 "Don't know"
  /QV517   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV517A  
     98 "Don't know"
  /QV517B  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV518   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV518AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV518AN 
     98 "Don't know"
  /QV520   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV520A  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV521   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV521AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV521AN 
     98 "Don't know"
  /QV522   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV522AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV522AN 
     98 "Don't know"
  /QV523   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV523AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV523AN 
     98 "Don't know"
  /QV524   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV525   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV526   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV527   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV527AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV527AN 
     98 "Don't know"
  /QV527B  
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /QV527C  
      1 "Upper abdomen"
      2 "Lower abdomen"
      3 "All over the abdomen"
      8 "Don't know"
  /QV528   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV528AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV528AN 
     98 "Don't know"
  /QV528B  
      1 "Rapidly, within few days"
      2 "Slowly, over weeks"
      8 "Don't know"
  /QV529   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV530   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV530AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV530AN 
     98 "Don't know"
  /QV530B  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV531   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV532   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV532AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV532AN 
     98 "Don't know"
  /QV532B  
      1 "Suddenly"
      2 "Gradually"
      8 "Don't know"
  /QV533   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV533AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV533AN 
     97 "Lasted till death"
     98 "Don't know"
  /QV533B  
      1 "One side only"
      2 "Both sides"
      8 "Don't know"
  /QV534   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV535   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV536   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV536AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV536AN 
     98 "Don't know"
  /QV536B  
     98 "Don't know"
  /QV537   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV538   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV538AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV538AN 
     98 "Don't know"
  /QV538B  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV539   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV540   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV541   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV541AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV541AN 
     98 "Don't know"
  /QV542   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV543   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV544   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV545   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV545A  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV546   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV546AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV546AN 
     98 "Don't know"
  /QV547   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV548   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV549   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV550   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV551   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV551AU 
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV551AN 
     98 "Don't know"
  /QV551B  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV551C  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV552   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV553$1 
   'A' "Symptom"
   'B' "Symptom"
   'C' "Symptom"
   'D' "Symptom"
   'E' "Symptom"
   'F' "Symptom"
   'Y' "No more/none"
  /QV553$2 
   'A' "Symptom"
   'B' "Symptom"
   'C' "Symptom"
   'D' "Symptom"
   'E' "Symptom"
   'F' "Symptom"
   'Y' "No more/none"
  /QV553$3 
   'A' "Symptom"
   'B' "Symptom"
   'C' "Symptom"
   'D' "Symptom"
   'E' "Symptom"
   'F' "Symptom"
   'Y' "No more/none"
  /QV553$4 
   'A' "Symptom"
   'B' "Symptom"
   'C' "Symptom"
   'D' "Symptom"
   'E' "Symptom"
   'F' "Symptom"
   'Y' "No more/none"
  /QV553$5 
   'A' "Symptom"
   'B' "Symptom"
   'C' "Symptom"
   'D' "Symptom"
   'E' "Symptom"
   'F' "Symptom"
   'Y' "No more/none"
  /QV553$6 
   'A' "Symptom"
   'B' "Symptom"
   'C' "Symptom"
   'D' "Symptom"
   'E' "Symptom"
   'F' "Symptom"
   'Y' "No more/none"
  /QV553$7 
   'A' "Symptom"
   'B' "Symptom"
   'C' "Symptom"
   'D' "Symptom"
   'E' "Symptom"
   'F' "Symptom"
   'Y' "No more/none"
  /QV554   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV555   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV556   
      6 "Spiritual healing details"
  /QV602U  
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /QV602N  
     98 "Don't know"
  /QV602A  
      1 "Before child birth/abortion"
      2 "After child birth/abortion"
      7 "Not applicable"
      8 "Don't know/remember"
  /QV602BU 
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /QV602BN 
     98 "Don't know"
  /QV603U  
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /QV603N  
     98 "Don't know"
  /QV604   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV605   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV606   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV607   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV607A  
      1 "Pallor"
      2 "Jaundiced"
      3 "Blue"
  /QV608   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV608AU 
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /QV608AN 
     98 "Don't know"
  /QV608B  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV609   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV610   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV610AA 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV610AB 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV610AC 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV610AD 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV610AE 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV610AX 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV613   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV615U  
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /QV615N  
     98 "Don't know"
  /QV616   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV617   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV617A  
      1 "Few dark specks"
      2 "Streaks of blood"
      3 "Frank blood"
  /QV618   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV620   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV620AU 
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /QV620AN 
     98 "Don't know"
  /QV622   
      1 "Continuous"
      2 "Intermittent"
      3 "Very intensive"
      4 "Increasing in severity"
      6 "Other"
  /QV623   
   'A      ' "Head"
   'B      ' "Abdomen"
   'C      ' "Chest"
   'D      ' "Breast"
   'E      ' "Legs"
   'F      ' "All over"
   'G      ' "Back pain"
   'X      ' "Other"
  /QV624U  
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /QV624N  
     98 "Don't know"
  /QV625U  
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /QV625N  
     98 "Don't know"
  /QV625A  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV625B  
      1 "Before labour"
      2 "At time of labour"
      3 "At the day of delivery"
      4 "1 day after delivery"
      5 "2 days after delivery"
      6 "3 days or more after delivery"
      7 "Not applicable"
      8 "Don't know/don't remember"
  /QV626   
      6 "Pain in abdomen"
  /QV627   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV628   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV629   
      1 "Mild"
      2 "Moderate"
      3 "High"
      8 "Don't know"
  /QV630   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV633   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV634   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV634AU 
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /QV634AN 
     98 "Don't know"
  /QV635   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV636   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV637   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV638   
      6 "State of consciousness"
  /QV638A  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV638B  
     98 "Don't know"
  /QV638D  
      1 "1st trimester"
      2 "2nd trimester"
      3 "3rd trimester"
      8 "Don't know"
  /QV638E  
      1 "About 1 minute"
      2 "Less than 5 minutes"
      3 "5 minutes or more"
      8 "Don't know"
  /QV638F  
      1 "Focal"
      2 "Generalised"
      8 "Don't know"
  /QV640A  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV640B  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV640C  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV640D  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV641U  
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /QV641N  
     98 "Don't know"
  /QV642U  
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /QV642N  
     97 "Not applicable"
     98 "Don't know"
  /QV643   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV644   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV644A  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV645   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV645AA 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV645AB 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV645AC 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV645AD 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV645AX 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV702   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV703   
   'A        ' "Obstetrician/specialist"
   'B        ' "Doctor"
   'C        ' "Nurse/midwife/LHV"
   'D        ' "Community midwife"
   'E        ' "Dai-tba"
   'F        ' "Lady h.worker"
   'G        ' "Homeopath"
   'H        ' "Hakim"
   'I        ' "Dispenser/compounder"
   'X        ' "Other"
  /QV704   
      1 "For problem"
      2 "For check-up only"
      8 "Don't know"
  /QV705   
      6 "What was the problem"
  /QV706   
     98 "Don't know"
  /QV707   
     98 "Don't know"
  /QV708   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV709   
   'A             ' "Not necessary"
   'B             ' "Costs too much"
   'C             ' "Too far"
   'D             ' "No transport"
   'E             ' "No one to go with"
   'F             ' "Service not good"
   'G             ' "No time to go"
   'H             ' "Did not know where to go"
   'I             ' "Did not want to see a male doctor"
   'J             ' "Long waiting time"
   'K             ' "Not allowed to go"
   'X             ' "Other"
   'Z             ' "Don't know"
  /QV710   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV711   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV712   
      1 "Normal"
      2 "High"
      3 "Low"
      8 "Don't know"
  /QV713   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV714   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV715   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV716   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV717   
      1 "Went for abortion"
      2 "Took drugs"
      3 "Inserted object into vagina"
      6 "Other"
      8 "Don't know"
  /QV718   
      1 "Obstetrician/specialist"
      2 "Doctor"
      3 "Nurse/midwife/LHV"
      4 "Community midwife"
      5 "Dai-tba"
      6 "Lady h.worker"
      7 "Homeopath"
      8 "Hakim"
      9 "Dispenser/compounder"
     96 "Other"
  /QV720   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV721   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV722   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV726   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV727   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV728   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV729   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV730   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV731   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV732   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV733   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV734   
      1 "Yes"
      2 "No"
      7 "Not applicable"
      8 "Don't know"
  /QV802   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV803   
      1 "Before"
      2 "After"
      8 "Don't know"
  /QV804   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV805   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV806   
     11 "Her home"
     12 "Other home"
     21 "Govt.hospital"
     22 "RHC/MCH"
     26 "Other public"
     31 "Pvt. hospital/clinic"
     36 "Other private med."
     96 "Other"
     97 "Did not delivery"
  /QV807   
      1 "Obstetrician/specialist"
      2 "Doctor"
      3 "Nurse/midwife/LHV"
      4 "Community midwife"
      5 "Dai-tba"
      6 "Lady h.worker"
      7 "Homeopath"
      8 "Hakim"
      9 "Dispenser/Compounder"
     10 "Relatives/friends"
     96 "Other"
  /QV808   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV808A  
      1 "During labour"
      2 "After child birth"
  /QV808B  
      1 "Normal"
      2 "Assisted vaginal"
      3 "Caesarean section"
  /QV809   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV810   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV811   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV812   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV813   
     98 "Don't know"
  /QV814   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV815   
      1 "Expedite delivery of baby"
      2 "Expedite placenta coming"
      3 "To ease pain"
      4 "To reduce bleeding"
      6 "Other"
      8 "Don't know"
  /QV816   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV817   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV818   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV819   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV820   
      1 "Before"
      2 "After"
      8 "Don't know"
  /QV821   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV822   
      1 "Head"
      2 "Legs"
      3 "Shoulder"
      4 "Arms"
      5 "Caesarean section"
      8 "Don't know"
  /QV823   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV824U  
      1 "Minutes"
      2 "Hours"
      9 "Special answers"
  /QV824N  
     98 "Don't know"
  /QV825   
      1 "All"
      2 "Part"
      8 "Don't know"
  /QV826   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV827   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV828   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV829   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV830   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV831   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV832   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV833U  
      1 "Hours"
      2 "Days"
      9 "Special answers"
  /QV833N  
     98 "Don't know"
  /QV834   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV835   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV836U  
      1 "Hours"
      2 "Days"
      9 "Special answers"
  /QV836N  
     98 "Don't know"
  /QV837   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV838   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV839   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV840   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV841   
      1 "Before labour"
      2 "During childbirth"
      3 "After childbirth"
      4 "Did not get blood transfusion"
      8 "Don't know"
  /QV901   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV902   
      1 "Road / train accident"
      2 "Fall"
      3 "Drowning"
      4 "Severe burns / acid burns"
      5 "Poisoning"
      6 "Suffocation"
      7 "Cut / stabbed"
      8 "Beaten / punched / kicked"
      9 "Rape"
     10 "Shot with gun"
     11 "Dog bite"
     12 "Snake bite"
     13 "Insect bite"
     14 "Due to electrical shock/current"
     15 "Suicide"
     96 "Other"
  /QV903U  
      1 "Days"
      2 "Months"
      9 "Special answers"
  /QV903N  
     98 "Don't know"
  /QV904   
      1 "Hurt herself intentionally"
      2 "Someone hurt her"
      3 "Accident"
      8 "Don't know"
  /QV905   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV906   
      1 "Main cause"
      2 "Contributed"
      3 "Not important"
      8 "Don't know"
  /QV1001U 
      0 "Immediately"
      1 "Hours"
      2 "Days"
      3 "Months"
      9 "Special answers"
  /QV1001N 
     95 "Died immediately"
     98 "Don't know"
  /QV1002  
      1 "Not serious"
      2 "Somewhat serious"
      3 "Very serious"
      4 "Life threatening"
  /QV1003  
      1 "Thought she could die"
      2 "Did not think she could die"
  /QV1004  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1005  
   'A            ' "No treatment necessary"
   'B            ' "No treatment customary"
   'C            ' "Cost too much"
   'D            ' "Too far"
   'E            ' "No transport"
   'F            ' "No one to accompany"
   'G            ' "Family did not allow"
   'H            ' "Good care at home"
   'I            ' "Did not know where to go"
   'J            ' "No time to go"
   'K            ' "Have to go to a male doctor"
   'L            ' "Did not realize seriousness"
   'M            ' "Death"
   'X            ' "Other"
   'Z            ' "Don't know"
  /QV1006  
   'A          ' "Deceased herself"
   'B          ' "Husband"
   'C          ' "Mother in law/father in law"
   'D          ' "Mother / father"
   'E          ' "Sister / sister in law"
   'F          ' "Other husband's family"
   'G          ' "Deceased's family members"
   'H          ' "Relatives"
   'I          ' "Friends /neighbors"
   'J          ' "Dai / LHV / fieldworker"
   'X          ' "Other"
   'Y          ' "No one"
   'Z          ' "Don't know"
  /QV1007  
   'A         ' "Obstetrician/specialist"
   'B         ' "Doctor"
   'C         ' "Nurse/midwife/LHV"
   'D         ' "Community midwife"
   'E         ' "Dai-tba"
   'F         ' "Lady h.worker"
   'G         ' "Homeopath"
   'H         ' "Hakim"
   'I         ' "Dispenser/compounder"
   'J         ' "Spiritual healing"
   'X         ' "Other"
  /QV1008  
   'A       ' "Her home"
   'B       ' "Other home"
   'C       ' "Govt.hospital"
   'D       ' "RHC/MCH"
   'E       ' "Other public"
   'F       ' "Pvt. hospital/clinic"
   'G       ' "Other private med."
   'X       ' "Other"
   'Y       ' "No one"
   'Z       ' "Don't know"
  /QV1009  
   'A          ' "Deceased herself"
   'B          ' "Husband"
   'C          ' "Mother in law/father in law"
   'D          ' "Mother / father"
   'E          ' "Sister / sister in law"
   'F          ' "Other husband's family"
   'G          ' "Deceased's family members"
   'H          ' "Relatives"
   'I          ' "Friends /neighbors"
   'J          ' "Dai / LHV / fieldworker"
   'X          ' "Other"
   'Y          ' "No one"
   'Z          ' "Don't know"
  /QV1010U 
      1 "Hours"
      2 "Days"
      3 "Months"
      9 "Special answers"
  /QV1010N 
     98 "Don't know"
  /QV1011  
      1 "Yes, tried to go immediately/already at health facility"
      2 "No, waited"
      8 "Don't know"
  /QV1012  
   'A        ' "Hospital too far"
   'B        ' "Did not realize seriousness"
   'C        ' "Lack of funds"
   'D        ' "Have to go to a male doctor"
   'E        ' "Night time"
   'F        ' "No transport"
   'G        ' "Husband away"
   'H        ' "Need permission from elders"
   'X        ' "Other"
   'Z        ' "Don't know"
  /QV1013U 
      1 "Hours"
      2 "Days"
      9 "Special answers"
  /QV1013N 
     97 "Already at health facility"
     98 "Don't know"
  /QV1015  
     21 "Govt.hospital"
     22 "RHC/MCH"
     26 "Other public"
     31 "Pvt. hospital/clinic"
     36 "Other private med."
     96 "Other"
     98 "Don't know"
  /QV1016  
   'B         ' "Husband"
   'C         ' "Mother in law/father in law"
   'D         ' "Mother / father"
   'E         ' "Sister / sister in law"
   'F         ' "Other husband's family"
   'G         ' "Deceased's family members"
   'H         ' "Relatives"
   'I         ' "Friends /neighbors"
   'J         ' "Dai / LHV / fieldworker"
   'X         ' "Other"
   'Y         ' "No one"
   'Z         ' "Don't know"
  /QV1017  
    998 "Don't know"
  /QV1018  
   'A        ' "On foot"
   'B        ' "Private car/jeep"
   'C        ' "Bus"
   'D        ' "Train"
   'E        ' "Ambulance"
   'F        ' "Animal cart"
   'G        ' "Taxi/rented vehicle"
   'H        ' "Rickshaw"
   'I        ' "Motorcycle"
   'X        ' "Other"
   'Z        ' "Don't know"
  /QV1019  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1020U 
      1 "Minutes"
      2 "Hours"
      9 "Special answers"
  /QV1020N 
     98 "Don't know"
  /QV1021U 
      0 "Immediately"
      1 "Minutes"
      2 "Hours"
      9 "Special answers"
  /QV1021N 
     98 "Don't know"
  /QV1022A 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1022B 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1022C 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1022D 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1022E 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1022F 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1022G 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1022X 
      1 "Yes"
      2 "No"
  /QV1022Y 
      1 "Yes"
      2 "No"
  /QV1023  
      1 "Improved"
      2 "Stayed same"
      3 "Got worse"
      4 "Died"
  /QV1024U 
      0 "Immediately"
      1 "Minutes"
      2 "Hours"
      3 "Days"
      9 "Special answers"
  /QV1024N 
     98 "Don't know"
  /QV1025  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1026  
     21 "Govt.hospital"
     22 "RHC/MCH"
     26 "Other public"
     31 "Pvt. hospital/clinic"
     36 "Other private med."
     96 "Other"
  /QV1027U 
      0 "Immediately"
      1 "Minutes"
      2 "Hours"
      3 "Days"
      4 "Months"
      9 "Special answers"
  /QV1027N 
      0 "Immediately"
     98 "Don't know"
  /QV1028  
   'A          ' "No equipment for operation"
   'B          ' "High blood pressure"
   'C          ' "To get better care"
   'D          ' "No doctor was available"
   'E          ' "No arrangements for giving blood"
   'F          ' "No proper arrangements for resolving problem"
   'G          ' "Baby went higher"
   'H          ' "Part of baby came out"
   'I          ' "Baby passed stool inside uterus"
   'J          ' "Cervix did not open"
   'X          ' "Other"
   'Z          ' "Don't know"
  /QV1029  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1030  
   'A            ' "No treatment necessary"
   'B            ' "Not customary"
   'C            ' "Cost too much"
   'D            ' "Too far"
   'E            ' "No transport"
   'F            ' "No one to accompany"
   'G            ' "Family did not allow"
   'H            ' "Good care at home"
   'I            ' "Did not know where to go"
   'J            ' "No time to go"
   'K            ' "Have to go to a male doctor"
   'L            ' "Did not realize seriousness"
   'M            ' "Death"
   'X            ' "Other"
   'Z            ' "Don't know"
  /QV1031  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1032  
     21 "Govt.hospital"
     22 "RHC/MCH"
     26 "Other public"
     31 "Pvt. hospital/clinic"
     36 "Other private med."
     96 "Other"
     98 "Don't know"
  /QV1033  
   'B         ' "Husband"
   'C         ' "Mother in law/father in law"
   'D         ' "Mother / father"
   'E         ' "Sister / sister in law"
   'F         ' "Other husband's family"
   'G         ' "Deceased's family members"
   'H         ' "Relatives"
   'I         ' "Friends /neighbors"
   'J         ' "Dai / LHV / fieldworker"
   'X         ' "Other"
   'Y         ' "No one"
   'Z         ' "Don't know"
  /QV1034  
   'A       ' "On foot"
   'B       ' "Private car/jeep"
   'C       ' "Bus"
   'D       ' "Train"
   'E       ' "Ambulance"
   'F       ' "Animal cart"
   'G       ' "Taxi/rented vehicle"
   'H       ' "Rickshaw"
   'X       ' "Other"
   'Z       ' "Don't know"
  /QV1035  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1036U 
      0 "Immediately"
      1 "Minutes"
      2 "Hours"
      9 "Special answers"
  /QV1036N 
      0 "Immediately"
     98 "Don't know"
  /QV1037A 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1037B 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1037C 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1037D 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1037E 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1037F 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1037G 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1037X 
      1 "Yes"
      2 "No"
  /QV1037Y 
      1 "Yes"
      2 "No"
  /QV1038  
      1 "Improved"
      2 "Stayed same"
      3 "Got worse"
      4 "Died"
  /QV1039U 
      0 "Immediately"
      1 "Minutes"
      2 "Hours"
      3 "Days"
      9 "Special answers"
  /QV1039N 
      0 "Immediately"
     97 "Die before reaching hospital"
     98 "Don't know"
  /QV1040  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1041  
     21 "Govt.hospital"
     22 "RHC/MCH"
     26 "Other public"
     31 "Pvt. hospital/clinic"
     36 "Other private med."
     96 "Other"
     98 "Don't know"
  /QV1042  
   'A          ' "No equipment for operation"
   'B          ' "High blood pressure"
   'C          ' "To get better care"
   'D          ' "No doctor was available"
   'E          ' "No arrangements for giving blood"
   'F          ' "No proper arrangements for resolving problem"
   'G          ' "Baby went higher"
   'H          ' "Part of baby came out"
   'I          ' "Baby passed stool inside uterus"
   'J          ' "Cervix did not open"
   'X          ' "Other"
   'Z          ' "Don't know"
  /QV1043  
   990000 "990000+"
   999997 "No amount spent"
   999998 "Don't know"
  /QV1044  
   'A     ' "Family funds"
   'B     ' "Borrowed"
   'C     ' "Sold assets"
   'D     ' "Given by relatives/friends"
   'E     ' "Mortgaged property"
   'X     ' "Other"
   'Z     ' "Don't know"
  /QV1045  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QV1046  
      1 "On her way to next hospital"
      2 "On her way back to home"
      3 "At home"
      6 "Others"
      8 "Don't know"
  /QV1047U 
      1 "Hours"
      2 "Days"
      9 "Special answers"
  /QV1047N 
     98 "Don't know"
  /QVH101  
     11 "Piped - into dwelling"
     12 "Piped - to yard/plot"
     13 "Piped - to neighbor"
     14 "Piped - public tap / standpipe"
     21 "Tube well or borehole"
     31 "Dug well - protected"
     32 "Dug well - unprotected"
     41 "Spring - protected"
     42 "Spring - unprotected"
     51 "Rainwater"
     61 "Tanker truck"
     62 "Filtration plant"
     71 "Cart with small tank"
     81 "Surface water (river/dam/lake/pond/stream/canal/irrigation channel)"
     91 "Bottled water"
     96 "Other"
  /QVH102  
     11 "Piped - into dwelling"
     12 "Piped - into yard/plot"
     13 "Piped - to neighbor"
     14 "Piped - public tap / standpipe"
     21 "Tube well or borehole"
     31 "Dug well - protected"
     32 "Dug well - unprotected"
     41 "Spring - protected"
     42 "Spring - unprotected"
     51 "Rainwater"
     61 "Tanker truck"
     71 "Cart with small tank"
     81 "Surface water (river/dam/lake/pond/stream/canal/irrigation channel)"
     96 "Other"
  /QVH103  
      1 "In own dwelling"
      2 "In own yard/plot"
      3 "Elsewhere"
  /QVH104  
    996 "On premises"
    998 "Don't know"
  /QVH106  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QVH107  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QVH108  
   'A      ' "Boil"
   'B      ' "Add bleach/chlorine"
   'C      ' "Strain through a cloth"
   'D      ' "Use water filter (ceramic/sand/composite/etc.)"
   'E      ' "Solar disinfection"
   'F      ' "Let it stand and settle"
   'X      ' "Other"
   'Z      ' "Don't know"
  /QVH109  
     11 "Flush - to piped sewer system"
     12 "Flush - to septic tank"
     13 "Flush - to pit latrine"
     14 "Flush - to somewhere else"
     15 "Flush - don't know where"
     21 "Pit latrine - ventilated improved pit (VIP)"
     22 "Pit latrine - with slab"
     23 "Pit latrine - without slab/open pit"
     31 "Composting toilet"
     41 "Bucket toilet"
     51 "Hanging toilet/hanging latrine"
     61 "No facility/bush/field"
     96 "Other"
  /QVH110  
      1 "Yes"
      2 "No"
  /QVH111  
     95 "10 or more households"
     98 "Don't know"
  /QVH112  
      1 "In own dwelling"
      2 "In own yard/plot"
      3 "Elsewhere"
  /QVH113  
      1 "Electricity"
      2 "LPG"
      3 "Natural gas"
      4 "Biogas"
      5 "Kerosene"
      6 "Coal, lignite"
      7 "Charcoal"
      8 "Wood"
      9 "Straw/shrubs/grass"
     10 "Agricultural crop"
     11 "Animal dung"
     95 "No food cooked in household"
     96 "Other"
  /QVH114  
      1 "In the house"
      2 "In a separate building"
      3 "Outdoors"
      6 "Other"
  /QVH115  
      1 "Yes"
      2 "No"
  /QVH117  
      1 "Yes"
      2 "No"
  /QVH118A 
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /QVH118B 
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /QVH118C 
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /QVH118D 
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /QVH118E 
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /QVH118F 
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /QVH118G 
      0 "None"
     95 "95 or more"
     98 "Unknown"
  /QVH121A 
      1 "Yes"
      2 "No"
  /QVH121B 
      1 "Yes"
      2 "No"
  /QVH121C 
      1 "Yes"
      2 "No"
  /QVH121D 
      1 "Yes"
      2 "No"
  /QVH121E 
      1 "Yes"
      2 "No"
  /QVH121F 
      1 "Yes"
      2 "No"
  /QVH121G 
      1 "Yes"
      2 "No"
  /QVH121H 
      1 "Yes"
      2 "No"
  /QVH121I 
      1 "Yes"
      2 "No"
  /QVH121J 
      1 "Yes"
      2 "No"
  /QVH121K 
      1 "Yes"
      2 "No"
  /QVH121L 
      1 "Yes"
      2 "No"
  /QVH121M 
      1 "Yes"
      2 "No"
  /QVH121N 
      1 "Yes"
      2 "No"
  /QVH121O 
      1 "Yes"
      2 "No"
  /QVH121P 
      1 "Yes"
      2 "No"
  /QVH121Q 
      1 "Yes"
      2 "No"
  /QVH121R 
      1 "Yes"
      2 "No"
  /QVH122A 
      1 "Yes"
      2 "No"
  /QVH122B 
      1 "Yes"
      2 "No"
  /QVH122C 
      1 "Yes"
      2 "No"
  /QVH122D 
      1 "Yes"
      2 "No"
  /QVH122E 
      1 "Yes"
      2 "No"
  /QVH122F 
      1 "Yes"
      2 "No"
  /QVH122G 
      1 "Yes"
      2 "No"
  /QVH122H 
      1 "Yes"
      2 "No"
  /QVH122I 
      1 "Yes"
      2 "No"
  /QVH122J 
      1 "Yes"
      2 "No"
  /QVH142  
     11 "Earth/sand"
     12 "Dung"
     21 "Wood planks"
     22 "Palm/bamboo"
     31 "Parquet or polished wood"
     32 "Vinyl or asphalt strips"
     33 "Ceramic tiles"
     34 "Cement"
     35 "Carpet"
     36 "Chips/terrazzo"
     37 "Bricks"
     38 "Mats"
     39 "Marble"
     96 "Other"
  /QVH143  
     11 "No roof"
     12 "Thatch/palm leaf"
     13 "Sod/grass"
     21 "Rustic mat"
     22 "Palm/bamboo"
     23 "Wood planks"
     24 "Cardboard"
     31 "Asbestos"
     32 "Reinforced brick cement/rcc"
     33 "Metal"
     34 "Wood"
     35 "Calamine/cement fiber"
     36 "Ceramic tiles"
     37 "Cement/rcc"
     38 "Roofing shingles"
     96 "Other"
  /QVH144  
     11 "No walls"
     12 "Cane/palm/trunks"
     13 "Dirt"
     14 "Mud/stones"
     15 "Bamboo/sticks/mud"
     21 "Unbaked bricks/mud"
     22 "Bamboo with mud"
     23 "Stone with mud"
     24 "Uncovered adobe"
     25 "Plywood"
     26 "Reused wood"
     31 "Cement"
     32 "Stone with lime/cement"
     33 "Bricks"
     34 "Cement blocks"
     35 "Covered adobe"
     36 "Wood planks/shingles"
     96 "Other"
  /QCD06   
     95 "95 or more"
  /QCD09   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QCD10   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QCD10A  
      1 "At time of death"
      2 "Between 43 days up to 1 year before death"
      3 "Within 42 days before the death"
      4 "Unknown"
  /QCD11   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /QCD12BC 
   'A010' "Typhoid fever with other complications"
   'A014' "Paratyphoid fever, unspecified"
   'A059' "Bacterial foodborne intoxication, unspecified"
   'A061' "Chronic intestinal amebiasis"
   'A090' "Other and unspecified gastroenteritis and colitis of infectious origin"
   'A099' "Gastroenteritis and colitis of unspecified origin"
   'A153' "Tuberculosis of lung, confirmed by unspecified means"
   'A162' "Tuberculosis of lung, without mention of bacteriological or histological confirm"
   'A169' "Respiratory tuberculosis unspecified, without mention of bacteriological or hist"
   'A170' "Tuberculous meningitis"
   'A178' "Tuberculous meningoencephalitis"
   'A183' "Tuberculous peritonitis"
   'A19 ' "Miliary tuberculosis"
   'A199' "Miliary tuberculosis, unspecified"
   'A35 ' "Other tetanus"
   'A419' "Sepsis, unspecified organism"
   'A829' "Rabies, unspecified"
   'A86 ' "Unspecified viral encephalitis"
   'A979' "Dengue, unspecified"
   'B058' "Other measles complications"
   'B179' "Acute viral hepatitis, unspecified"
   'B181' "Chronic viral hepatitis B without delta-agent"
   'B182' "Chronic viral hepatitis C"
   'B189' "Chronic viral hepatitis, unspecified"
   'B190' "Unspecified viral hepatitis with hepatic coma"
   'B24 ' "Unspecified human immunodeficiency virus [HIV] disease"
   'C069' "Malignant neoplasm of mouth, unspecified"
   'C109' "Malignant neoplasm of oropharynx, unspecified"
   'C140' "Malignant neoplasm of pharynx, unspecified"
   'C159' "Malignant neoplasm of esophagus, unspecified"
   'C169' "Malignant neoplasm of stomach, unspecified"
   'C189' "Malignant neoplasm of colon, unspecified"
   'C20 ' "Malignant neoplasm of rectum"
   'C210' "Malignant neoplasm of anus, unspecified"
   'C220' "Liver cell carcinoma"
   'C229' "Malig neoplasm of liver, not specified as primary or sec"
   'C259' "Malignant neoplasm of pancreas, unspecified"
   'C260' "Malignant neoplasm of intestinal tract, part unspecified"
   'C269' "Malignant neoplasm of ill-defined sites within the dgstv sys"
   'C349' "Malignant neoplasm of unsp part of right bronchus or lung"
   'C409' "Malig neoplasm of unsp bones and artic cartlg of left limb"
   'C419' "Malignant neoplasm of bone and articular cartilage, unsp"
   'C449' "Other specified malignant neoplasm of skin, unspecified"
   'C509' "Malignant neoplasm of unsp site of unspecified male breast"
   'C539' "Malignant neoplasm of cervix uteri, unspecified"
   'C55 ' "Malignant neoplasm of uterus, part unspecified"
   'C56 ' "Malignant neoplasm of ovary"
   'C579' "Malignant neoplasm of female genital organ, unspecified"
   'C64 ' "Malignant neoplasm of kidney, except renal pelvis"
   'C679' "Malignant neoplasm of bladder, unspecified"
   'C719' "Malignant neoplasm of brain, unspecified"
   'C721' "Malignant neoplasm of cauda equina"
   'C762' "Malignant neoplasm of abdomen"
   'C765' "Malignant neoplasm of right lower limb"
   'C794' "Secondary malignant neoplasm of oth parts of nervous system"
   'C795' "Secondary malignant neoplasm of bone marrow"
   'C799' "Secondary malignant neoplasm of unspecified site"
   'C809' "Malignant neoplasm, primary site unspecified"
   'C85 ' "Other and unspecified types of non-Hodgkin lymphoma"
   'C859' "Non-Hodgkin lymphoma, unspecified, intrapelvic lymph nodes"
   'C915' "Adult T-cell lymphoma/leukemia (HTLV-1-assoc), in remission"
   'C959' "Leukemia, unspecified not having achieved remission"
   'C969' "Malig neoplm of lymphoid, hematpoetc and rel tissue, unsp"
   'D022' "Carcinoma in situ of left bronchus and lung"
   'D380' "Neoplasm of uncertain behavior of larynx"
   'D432' "Neoplasm of uncertain behavior of brain, unspecified"
   'D434' "Neoplasm of uncertain behavior of spinal cord"
   'D440' "Neoplasm of uncertain behavior of thyroid gland"
   'D45 ' "Polycythemia vera"
   'D561' "Beta thalassemia"
   'D569' "Thalassemia, unspecified"
   'D619' "Aplastic anemia, unspecified"
   'D649' "Anemia, unspecified"
   'D66 ' "Hereditary factor VIII deficiency"
   'D696' "Thrombocytopenia, unspecified"
   'D70 ' "Agranulocytosis"
   'E059' "Thyrotoxicosis, unspecified with thyrotoxic crisis or storm"
   'E079' "Disorder of thyroid, unspecified"
   'E10 ' "diabetes mellitus Type I"
   'E102' "Type 1 diabetes mellitus w oth diabetic kidney complication"
   'E106' "Type 1 diabetes mellitus with hypoglycemia without coma"
   'E107' "Family history of diseases of the digestive system"
   'E108' "Type 1 diabetes mellitus with unspecified complications"
   'E11 ' "diabetes mellitus"
   'E111' "Type 2 diabetes mellitus with ketoacidosis with coma"
   'E112' "Type 2 diabetes mellitus with diabetic nephropathy"
   'E115' "Type 2 diabetes w diabetic peripheral angiopathy w gangrene"
   'E116' "Type 2 diabetes mellitus with other oral complications"
   'E118' "Type 2 diabetes mellitus with unspecified complications"
   'E132' "Oth diabetes mellitus with oth diabetic kidney complication"
   'E138' "Oth diabetes mellitus with unspecified complications"
   'E14 ' "Diabetes mellitus"
   'E142' "Diabetes mellitus With renal complications"
   'E144' "Diabetes mellitus With neurological complications"
   'E146' "Diabetes mellitus With other specified complications"
   'E148' "Diabetes mellitus With unspecified complications"
   'E43 ' "Unspecified severe protein-calorie malnutrition"
   'E668' "Other obesity"
   'E669' "Obesity, unspecified"
   'F323' "Major depressv disord, single epsd, severe w psych features"
   'F332' "Major depressv disorder, recurrent severe w/o psych features"
   'F333' "Major depressv disorder, recurrent, severe w psych symptoms"
   'F819' "Developmental disorder of scholastic skills, unspecified"
   'G039' "Meningitis, unspecified"
   'G09 ' "Sequelae of inflammatory diseases of central nervous system"
   'G409' "Epilepsy, unsp, intractable, without status epilepticus"
   'G710' "Muscular dystrophy"
   'G809' "Cerebral palsy, unspecified"
   'G919' "Hydrocephalus, unspecified"
   'G948' "Other specified disorders of brain in diseases classified elsewhere"
   'I081' "Rheumatic disorders of both mitral and tricuspid valves"
   'I082' "Rheumatic disorders of both aortic and tricuspid valves"
   'I083' "Comb rheumatic disord of mitral, aortic and tricuspid valves"
   'I088' "Other rheumatic multiple valve diseases"
   'I099' "Rheumatic heart disease, unspecified"
   'I10 ' "Essential (primary) hypertension"
   'I100' "Pre-existing essential hypertension complicating pregnancy, childbirth and the p"
   'I110' "Hypertensive heart disease with heart failure"
   'I120' "Hyp chr kidney disease w stage 5 chr kidney disease or ESRD"
   'I159' "Secondary hypertension, unspecified"
   'I209' "Angina pectoris, unspecified"
   'I219' "Acute myocardial infarction, unspecified"
   'I259' "Chronic ischemic heart disease, unspecified"
   'I269' "Septic pulmonary embolism without acute cor pulmonale"
   'I429' "Cardiomyopathy, unspecified"
   'I469' "Cardiac arrest, cause unspecified"
   'I500' "Congestive heart failure"
   'I509' "Heart failure, unspecified"
   'I519' "Heart disease, unspecified"
   'I607' "Nontraumatic subarachnoid haemorrhage from unsp intracran art"
   'I608' "Other nontraumatic subarachnoid haemorrhage"
   'I619' "Nontraumatic intracerebral haemorrhage, unspecified"
   'I629' "Nontraumatic intracranial haemorrhage, unspecified"
   'I64 ' "Stroke, not specified as haemorrhage or infarction"
   'I670' "Dissection of cerebral arteries, nonruptured"
   'I802' "Phlebitis and thrombophlebitis of unspecified popliteal vein"
   'I959' "Hypotension, unspecified"
   'J188' "Other pneumonia, unspecified organism"
   'J189' "Pneumonia, unspecified organism"
   'J440' "Chronic obstructive pulmon disease w acute lower resp infct"
   'J441' "Chronic obstructive pulmonary disease w (acute) exacerbation"
   'J448' "Other specified chronic obstructive pulmonary disease"
   'J449' "Chronic obstructive pulmonary disease, unspecified"
   'J459' "Exercise induced bronchospasm"
   'J46 ' "Status asthmaticus"
   'J690' "Pneumonitis due to inhalation of food and vomit"
   'J841' "Idiopathic interstitial pneumonia, not otherwise specified"
   'J90 ' "Pleural effusion, not elsewhere classified"
   'J969' "Respiratory failure, unspecified with hypercapnia"
   'K027' "Dental root caries"
   'K352' "Acute appendicitis with generalised peritonitis"
   'K358' "Other acute appendicitis"
   'K37 ' "Unspecified appendicitis"
   'K565' "Intestinal adhesions [bands] with complete obstruction"
   'K566' "Other intestnl obst unsp as to partial versus complete obst"
   'K631' "Perforation of intestine (nontraumatic)"
   'K659' "Peritonitis, unspecified"
   'K721' "Chronic hepatic failure without coma"
   'K729' "Hepatic failure, unspecified without coma"
   'K739' "Chronic hepatitis, unspecified"
   'K746' "Unspecified cirrhosis of liver"
   'K759' "Inflammatory liver disease, unspecified"
   'K769' "Liver disease, unspecified"
   'K801' "Calculus of gallbladder w oth cholecystitis w/o obstruction"
   'K859' "Acute pancreatitis with infected necrosis, unspecified"
   'K920' "Hematemesis"
   'K922' "Gastrointestinal haemorrhage, unspecified"
   'L100' "Pemphigus vulgaris"
   'L899' "Pressure ulcer of unspecified site, stage 1"
   'M069' "Rheumatoid arthritis, unspecified"
   'M321' "Endocarditis in systemic lupus erythematosus"
   'M359' "Systemic involvement of connective tissue, unspecified"
   'M629' "Disorder of muscle, unspecified"
   'N049' "Nephrotic syndrome with unspecified morphologic changes"
   'N142' "Neuropath induced by unsp drug, medicament or biolg sub"
   'N179' "Acute kidney failure, unspecified"
   'N185' "Chronic kidney disease, stage 5"
   'N189' "Chronic kidney disease, unspecified"
   'N19 ' "Unspecified kidney failure"
   'N200' "Calculus of kidney"
   'N390' "Urinary tract infection, site not specified"
   'O00 ' "Ectopic pregnancy"
   'O008' "Other ectopic pregnancy without intrauterine pregnancy"
   'O019' "Hydatidiform mole, unspecified"
   'O031' "Delayed or excessive hemor following incmpl spon abortion"
   'O035' "Genitl trct and pelvic infct fol complete or unsp spon abort"
   'O06 ' "Unspecified abortion"
   'O063' "Unspecified abortion Complete or unspecified, with other and unspecified complic"
   'O068' "Unspecified abortion, Complete or unspecified, with other and unspecified compli"
   'O07 ' "Complete or unspecified, with other and unspecified complications"
   'O070' "Genitl trct and pelvic infct fol failed attempt term of preg"
   'O075' "Other and unspecified failed attempted abortion, complicated by genital tract an"
   'O101' "Pre-existing hypertensive heart disease comp childbirth"
   'O11 ' "Pre-eclampsia superimposed on chronic hypertension"
   'O13 ' "Gestational [pregnancy-induced] hypertension"
   'O141' "Severe pre-eclampsia, third trimester"
   'O150' "Eclampsia complicating pregnancy, second trimester"
   'O152' "Eclampsia complicating the puerperium"
   'O159' "Eclampsia, unspecified as to time period"
   'O211' "Hyperemesis gravidarum with metabolic disturbance"
   'O223' "Deep phlebothrombosis in pregnancy, third trimester"
   'O244' "Gestational diabetes mellitus in childbirth, unsp control"
   'O441' "Complete placenta previa with haemorrhage, third trimester"
   'O458' "Other premature separation of placenta, second trimester"
   'O459' "Premature separation of placenta, unsp, third trimester"
   'O468' "Other antepartum haemorrhage, unspecified trimester"
   'O469' "Antepartum haemorrhage, unspecified, unspecified trimester"
   'O639' "Long labor, unspecified"
   'O669' "Obstructed labor, unspecified"
   'O670' "Intrapartum haemorrhage with coagulation defect"
   'O711' "Rupture of uterus during labor"
   'O72 ' "Postpartum haemorrhage"
   'O720' "Third-stage haemorrhage"
   'O721' "Other immediate postpartum haemorrhage"
   'O722' "Delayed and secondary postpartum haemorrhage"
   'O731' "Retained portions of placenta and membranes, w/o haemorrhage"
   'O759' "Complication of labor and delivery, unspecified"
   'O85 ' "Puerperal sepsis"
   'O860' "Infection of obstetric surgical wound"
   'O871' "Deep phlebothrombosis in the puerperium"
   'O882' "Thromboembolism in pregnancy, unspecified trimester"
   'O900' "Disruption of cesarean delivery wound"
   'O909' "Complication of the puerperium, unspecified"
   'O990' "Anemia complicating the puerperium"
   'O994' "Diseases of the circulatory system complicating childbirth"
   'Q223' "Other congenital malformations of pulmonary valve"
   'Q240' "Dextrocardia"
   'Q249' "Congenital malformation of heart, unspecified"
   'R100' "Acute abdomen"
   'R104' "Other and unspecified abdominal pain"
   'R11 ' "Nausea and vomiting"
   'R17 ' "Unspecified jaundice"
   'R465' "Suspiciousness and marked evasiveness"
   'R509' "Fever, unspecified"
   'R51 ' "Headache"
   'R572' "Septic shock"
   'R69 ' "Illness, unspecified"
   'R96 ' "Other sudden death, cause unknown"
   'R99 ' "Ill-defined and unknown cause of mortality"
   'S068' "Intcran inj w loss of consciousness of 1-5 hrs 59 min, init"
   'S099' "Unspecified injury of face, initial encounter"
   'T060' "Injuries of brain and cranial nerves with injuries of nerves and spinal cord at"
   'T179' "Gastr contents in resp tract, part unsp cause oth inj, sqla"
   'T289' "Corrosions of left ear drum, subsequent encounter"
   'T290' "Burns of multiple regions, unspecified degree"
   'T292' "Burns of multiple regions, no more than second-degree burns mentioned"
   'T300' "Burn of unspecified body region, unspecified degree"
   'T318' "Burns of 80-89% of body surface w 60-69% third degree burns"
   'T630' "Toxic effect of venom of Australian snake, acc, sequela"
   'T659' "Toxic effect of unsp substance, self-harm, sequela"
   'T670' "Heatstroke and sunstroke, subsequent encounter"
   'T750' "Other effects of lightning, sequela"
   'T754' "Electrocution, sequela"
   'T804' "Rh incompatibility w hemolytic transfs react, unsp, subs"
   'T808' "Extravasation of other vesicant agent, initial encounter"
   'T809' "Unspecified transfusion reaction, initial encounter"
   'T886' "Anaphyl reaction due to advrs eff drug/med prop admin, init"
   'T887' "Unspecified adverse effect of drug or medicament, sequela"
   'T889' "Complication of surgical and medical care, unsp, sequela"
   'T909' "Sequelae of unspecified injury of head"
   'V862' "Person on outside of sp off-rd mv injured in traf, sequela"
   'V878' "Person injured in oth nonclsn transport acc w mtr veh, init"
   'V892' "Person injured in unsp motor-vehicle accident, traffic, init"
   'W34 ' "Discharge from other and unspecified firearms"
   'W86 ' "Exposure to other specified electric current"
   'X00 ' "Exposure to uncontrolled fire in building or structure"
   'X09 ' "Exposure to unspecified smoke, fire and flames"
   'X380' "Victim of flood"
   'X68 ' "Intentional self-poisoning by and exposure to pesticides"
   'X70 ' "Intentional self-harm by hanging, strangulation and suffocation"
   'X71 ' "Intentional self-harm by drowning and submersion"
   'X72 ' "Intentional self-harm by handgun discharge"
   'X74 ' "Intentional self-harm by other and unspecified firearm discharge"
   'X76 ' "Intentional self-harm by smoke, fire and flames"
   'X80 ' "Intentional self-harm by jumping from a high place"
   'X81 ' "Intentional self-harm by jumping or lying before moving object"
   'X83 ' "Intentional self-harm by other specified means"
   'X84 ' "Intentional self-harm by jumping or lying before moving object"
   'X91 ' "Assault by hanging, strangulation and suffocation"
   'X95 ' "Assault by other and unspecified firearm discharge"
   'Y08 ' "Assault by other specified means"
   'Y09 ' "Assault by unspecified means"
   'Y20 ' "Hanging, strangulation and suffocation, undetermined intent"
   'Y30 ' "Falling, jumping or pushed from a high place, undetermined intent"
   'Y364' "War operations involving rubber bullets, civilian, sequela"
   'Y600' "During surgical operation"
   'Y601' "During infusion or transfusion"
   'Y603' "During injection or immunization"
   'Y609' "During unspecified surgical and medical care"
   'Y792' "Prosth/oth implnt/mtrls orthopedic devices assoc w incdt"
   'Y831' "Implnt of artif int dev cause abn react/compl, w/o misadvnt"
   'Z605' "Target of (perceived) adverse discrimination and persecution"
   'Z915' "Personal history of self-harm"
  /QCD13C  
      1 "Direct obstetric death"
      2 "Indirect obstetric death"
      3 "Probable obstetric death"
      4 "Coincidental obstetric death"
      5 "Late maternal death"
      6 "Non-obstetric death"
      0 "Undecided on the category of death"
  /QCD13D  
      1 "Death during pregnancy (before any signs of labor or abortion)"
      2 "Death during or < 24 hours after delivery"
      3 "Death during or < 24 hours after abortion/miscarriage"
      4 "Death > 24 hours but < 42 days after delivery"
      5 "Death > 24 hours but < 42 days after abortion/miscarriage"
      6 "Death > 42 days but < 1 year after delivery/abortion/miscarriage"
      0 "Cannot be determined (insufficient information)"
      9 "Not applicable (not a pregnancy-related death)"
  /QCD13E1 
      1 "Yes"
      2 "No"
      3 "Probably"
      6 "Cannot Determine"
      7 "Not Applicable (deaths not pregnancy related)"
  /QCD13E2 
      1 "Yes"
      2 "No"
      3 "Probably"
      6 "Cannot Determine"
      7 "Not Applicable (deaths not pregnancy related)"
  /QCD13E3 
      1 "Yes"
      2 "No"
      3 "Probably"
      6 "Cannot Determine"
      7 "Not Applicable (deaths not pregnancy related)"
  /QCD14   
      1 "Very Poor"
      2 "Poor"
      3 "Average"
      4 "Good"
      5 "Very Good"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\PK7A\PKVA7AFL.sav'.
